load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_library(
    name = "main",
    srcs = ["cpp/main.cpp"],
    deps = [
        "//thirdparty/catch2",
    ],
)

cc_test(
    name = "wpinet_tests",
    size = "small",
    srcs = glob(
        [
            "cpp/**/*.cpp",
            "cpp/**/*.hpp",
        ],
        exclude = [
            "cpp/main.cpp",
            "cpp/MulticastTest.cpp",
        ],
    ),
    tags = ["no-asan"],
    deps = [
        ":main",
        "//thirdparty/catch2",
        "//wpinet",
        "//wpiutil/src/test/native:wpiutil-testlib",
    ],
)

cc_test(
    name = "wpinet_multicast_tests",
    size = "small",
    srcs = ["cpp/MulticastTest.cpp"],
    tags = [
        "no-asan",
        "no-remote-exec",  # requires avahi-daemon
    ],
    deps = [
        ":main",
        "//thirdparty/catch2",
        "//wpinet",
    ],
)

test_suite(
    name = "native",
    tests = [
        ":wpinet_multicast_tests",
        ":wpinet_tests",
    ],
)
