/*----------------------------------------------------------------------------*/
/* Copyright (c) 2019 FIRST. All Rights Reserved.                             */
/* Open Source Software - may be modified and shared by FRC teams. The code   */
/* must be accompanied by the FIRST BSD license file in the root directory of */
/* the project.                                                               */
/*----------------------------------------------------------------------------*/

#pragma once

namespace frc {

/**
 * Represents colors that can be used with Addressable LEDs.
 */
class Color {
 public:
  /**
   * Constructs a Color.
   *
   * @param red Red value (0-255)
   * @param green Green value (0-255)
   * @param blue Blue value (0-255)
   */
  constexpr Color(int r, int g, int b) : red(r), green(g), blue(b) {}

  static const Color kAliceBlue;
  static const Color kAntiqueWhite;
  static const Color kAqua;
  static const Color kAquamarine;
  static const Color kAzure;
  static const Color kBeige;
  static const Color kBisque;
  static const Color kBlack;
  static const Color kBlanchedAlmond;
  static const Color kBlue;
  static const Color kBlueViolet;
  static const Color kBrown;
  static const Color kBurlywood;
  static const Color kCadetBlue;
  static const Color kChartreuse;
  static const Color kChocolate;
  static const Color kCoral;
  static const Color kCornflowerBlue;
  static const Color kCornsilk;
  static const Color kCrimson;
  static const Color kCyan;
  static const Color kDarkBlue;
  static const Color kDarkCyan;
  static const Color kDarkGoldenrod;
  static const Color kDarkGray;
  static const Color kDarkGreen;
  static const Color kDarkGrey;
  static const Color kDarkKhaki;
  static const Color kDarkMagenta;
  static const Color kDarkOliveGreen;
  static const Color kDarkOrange;
  static const Color kDarkOrchid;
  static const Color kDarkRed;
  static const Color kDarkSalmon;
  static const Color kDarkSeaGreen;
  static const Color kDarkSlateBlue;
  static const Color kDarkSlateGray;
  static const Color kDarkSlateGrey;
  static const Color kDarkTurquoise;
  static const Color kDarkViolet;
  static const Color kDeepPink;
  static const Color kDeepSkyBlue;
  static const Color kDenim;
  static const Color kDimGray;
  static const Color kDimGrey;
  static const Color kDodgerBlue;
  static const Color kFirebrick;
  static const Color kFloralWhite;
  static const Color kForestGreen;
  static const Color kFuchsia;
  static const Color kGainsboro;
  static const Color kGhostWhite;
  static const Color kGold;
  static const Color kGoldenrod;
  static const Color kGray;
  static const Color kGreen;
  static const Color kGreenYellow;
  static const Color kGrey;
  static const Color kHoneydew;
  static const Color kHotPink;
  static const Color kIndianRed;
  static const Color kIndigo;
  static const Color kIvory;
  static const Color kKhaki;
  static const Color kLavender;
  static const Color kLavenderBlush;
  static const Color kLawnGreen;
  static const Color kLemonChiffon;
  static const Color kLightBlue;
  static const Color kLightCoral;
  static const Color kLightCyan;
  static const Color kLightGoldenrodYellow;
  static const Color kLightGray;
  static const Color kLightGreen;
  static const Color kLightGrey;
  static const Color kLightPink;
  static const Color kLightSalmon;
  static const Color kLightSeagGeen;
  static const Color kLightSkyBlue;
  static const Color kLightSlateGray;
  static const Color kLightSlateGrey;
  static const Color kLightSteellue;
  static const Color kLightYellow;
  static const Color kLime;
  static const Color kLimeGreen;
  static const Color kLinen;
  static const Color kMagenta;
  static const Color kMaroon;
  static const Color kMediumAquamarine;
  static const Color kMediumBlue;
  static const Color kMediumOrchid;
  static const Color kMediumPurple;
  static const Color kMediumSeaGreen;
  static const Color kMediumSlateBlue;
  static const Color kMediumSpringGreen;
  static const Color kMediumTurquoise;
  static const Color kMediumVioletRed;
  static const Color kMidnightBlue;
  static const Color kMintcream;
  static const Color kMistyRose;
  static const Color kMoccasin;
  static const Color kNavajoWhite;
  static const Color kNavy;
  static const Color kOldlace;
  static const Color kOlive;
  static const Color kOliveDrab;
  static const Color kOrange;
  static const Color kOrangeRed;
  static const Color kOrchid;
  static const Color kPaleGoldenrod;
  static const Color kPaleGreen;
  static const Color kPaleTurquoise;
  static const Color kPaleVioletRed;
  static const Color kPapayaWhip;
  static const Color kPeachpuff;
  static const Color kPeru;
  static const Color kPink;
  static const Color kPlum;
  static const Color kPowderBlue;
  static const Color kPurple;
  static const Color kRed;
  static const Color kRosyBrown;
  static const Color kRoyalBlue;
  static const Color kSaddleBrown;
  static const Color kSalmon;
  static const Color kSandyBrown;
  static const Color kSeaGreen;
  static const Color kSeashell;
  static const Color kSienna;
  static const Color kSilver;
  static const Color kSkyBlue;
  static const Color kSlateBlue;
  static const Color kSlateGray;
  static const Color kSlateGrey;
  static const Color kSnow;
  static const Color kSpringGreen;
  static const Color kSteelBlue;
  static const Color kTan;
  static const Color kTeal;
  static const Color kThistle;
  static const Color kTomato;
  static const Color kTurquoise;
  static const Color kViolet;
  static const Color kWheat;
  static const Color kWhite;
  static const Color kWhiteSmoke;
  static const Color kYellow;
  static const Color kYellowGreen;

  int red;
  int green;
  int blue;
};

constexpr Color Color::kAliceBlue{240, 248, 255};
constexpr Color Color::kAntiqueWhite{250, 235, 215};
constexpr Color Color::kAqua{0, 255, 255};
constexpr Color Color::kAquamarine{127, 255, 212};
constexpr Color Color::kAzure{240, 255, 255};
constexpr Color Color::kBeige{245, 245, 220};
constexpr Color Color::kBisque{255, 228, 196};
constexpr Color Color::kBlack{0, 0, 0};
constexpr Color Color::kBlanchedAlmond{255, 235, 205};
constexpr Color Color::kBlue{0, 0, 255};
constexpr Color Color::kBlueViolet{138, 43, 226};
constexpr Color Color::kBrown{165, 42, 42};
constexpr Color Color::kBurlywood{222, 184, 135};
constexpr Color Color::kCadetBlue{95, 158, 160};
constexpr Color Color::kChartreuse{127, 255, 0};
constexpr Color Color::kChocolate{210, 105, 30};
constexpr Color Color::kCoral{255, 127, 80};
constexpr Color Color::kCornflowerBlue{100, 149, 237};
constexpr Color Color::kCornsilk{255, 248, 220};
constexpr Color Color::kCrimson{220, 20, 60};
constexpr Color Color::kCyan{0, 255, 255};
constexpr Color Color::kDarkBlue{0, 0, 139};
constexpr Color Color::kDarkCyan{0, 139, 139};
constexpr Color Color::kDarkGoldenrod{184, 134, 11};
constexpr Color Color::kDarkGray{169, 169, 169};
constexpr Color Color::kDarkGreen{0, 100, 0};
constexpr Color Color::kDarkGrey{169, 169, 169};
constexpr Color Color::kDarkKhaki{189, 183, 107};
constexpr Color Color::kDarkMagenta{139, 0, 139};
constexpr Color Color::kDarkOliveGreen{85, 107, 47};
constexpr Color Color::kDarkOrange{255, 140, 0};
constexpr Color Color::kDarkOrchid{153, 50, 204};
constexpr Color Color::kDarkRed{139, 0, 0};
constexpr Color Color::kDarkSalmon{233, 150, 122};
constexpr Color Color::kDarkSeaGreen{143, 188, 143};
constexpr Color Color::kDarkSlateBlue{72, 61, 139};
constexpr Color Color::kDarkSlateGray{47, 79, 79};
constexpr Color Color::kDarkSlateGrey{47, 79, 79};
constexpr Color Color::kDarkTurquoise{0, 206, 209};
constexpr Color Color::kDarkViolet{148, 0, 211};
constexpr Color Color::kDeepPink{255, 20, 147};
constexpr Color Color::kDeepSkyBlue{0, 191, 255};
constexpr Color Color::kDenim{21, 96, 189};
constexpr Color Color::kDimGray{105, 105, 105};
constexpr Color Color::kDimGrey{105, 105, 105};
constexpr Color Color::kDodgerBlue{30, 144, 255};
constexpr Color Color::kFirebrick{178, 34, 34};
constexpr Color Color::kFloralWhite{255, 250, 240};
constexpr Color Color::kForestGreen{34, 139, 34};
constexpr Color Color::kFuchsia{255, 0, 255};
constexpr Color Color::kGainsboro{220, 220, 220};
constexpr Color Color::kGhostWhite{248, 248, 255};
constexpr Color Color::kGold{255, 215, 0};
constexpr Color Color::kGoldenrod{218, 165, 32};
constexpr Color Color::kGray{128, 128, 128};
constexpr Color Color::kGreen{0, 128, 0};
constexpr Color Color::kGreenYellow{173, 255, 47};
constexpr Color Color::kGrey{128, 128, 128};
constexpr Color Color::kHoneydew{240, 255, 240};
constexpr Color Color::kHotPink{255, 105, 180};
constexpr Color Color::kIndianRed{205, 92, 92};
constexpr Color Color::kIndigo{75, 0, 130};
constexpr Color Color::kIvory{255, 255, 240};
constexpr Color Color::kKhaki{240, 230, 140};
constexpr Color Color::kLavender{230, 230, 250};
constexpr Color Color::kLavenderBlush{255, 240, 245};
constexpr Color Color::kLawnGreen{124, 252, 0};
constexpr Color Color::kLemonChiffon{255, 250, 205};
constexpr Color Color::kLightBlue{173, 216, 230};
constexpr Color Color::kLightCoral{240, 128, 128};
constexpr Color Color::kLightCyan{224, 255, 255};
constexpr Color Color::kLightGoldenrodYellow{250, 250, 210};
constexpr Color Color::kLightGray{211, 211, 211};
constexpr Color Color::kLightGreen{144, 238, 144};
constexpr Color Color::kLightGrey{211, 211, 211};
constexpr Color Color::kLightPink{255, 182, 193};
constexpr Color Color::kLightSalmon{255, 160, 122};
constexpr Color Color::kLightSeagGeen{32, 178, 170};
constexpr Color Color::kLightSkyBlue{135, 206, 250};
constexpr Color Color::kLightSlateGray{119, 136, 153};
constexpr Color Color::kLightSlateGrey{119, 136, 153};
constexpr Color Color::kLightSteellue{176, 196, 222};
constexpr Color Color::kLightYellow{255, 255, 224};
constexpr Color Color::kLime{0, 255, 0};
constexpr Color Color::kLimeGreen{50, 205, 50};
constexpr Color Color::kLinen{250, 240, 230};
constexpr Color Color::kMagenta{255, 0, 255};
constexpr Color Color::kMaroon{128, 0, 0};
constexpr Color Color::kMediumAquamarine{102, 205, 170};
constexpr Color Color::kMediumBlue{0, 0, 205};
constexpr Color Color::kMediumOrchid{186, 85, 211};
constexpr Color Color::kMediumPurple{147, 112, 219};
constexpr Color Color::kMediumSeaGreen{60, 179, 113};
constexpr Color Color::kMediumSlateBlue{123, 104, 238};
constexpr Color Color::kMediumSpringGreen{0, 250, 154};
constexpr Color Color::kMediumTurquoise{72, 209, 204};
constexpr Color Color::kMediumVioletRed{199, 21, 133};
constexpr Color Color::kMidnightBlue{25, 25, 112};
constexpr Color Color::kMintcream{245, 255, 250};
constexpr Color Color::kMistyRose{255, 228, 225};
constexpr Color Color::kMoccasin{255, 228, 181};
constexpr Color Color::kNavajoWhite{255, 222, 173};
constexpr Color Color::kNavy{0, 0, 128};
constexpr Color Color::kOldlace{253, 245, 230};
constexpr Color Color::kOlive{128, 128, 0};
constexpr Color Color::kOliveDrab{107, 142, 35};
constexpr Color Color::kOrange{255, 165, 0};
constexpr Color Color::kOrangeRed{255, 69, 0};
constexpr Color Color::kOrchid{218, 112, 214};
constexpr Color Color::kPaleGoldenrod{238, 232, 170};
constexpr Color Color::kPaleGreen{152, 251, 152};
constexpr Color Color::kPaleTurquoise{175, 238, 238};
constexpr Color Color::kPaleVioletRed{219, 112, 147};
constexpr Color Color::kPapayaWhip{255, 239, 213};
constexpr Color Color::kPeachpuff{255, 218, 185};
constexpr Color Color::kPeru{205, 133, 63};
constexpr Color Color::kPink{255, 192, 203};
constexpr Color Color::kPlum{221, 160, 221};
constexpr Color Color::kPowderBlue{176, 224, 230};
constexpr Color Color::kPurple{128, 0, 128};
constexpr Color Color::kRed{255, 0, 0};
constexpr Color Color::kRosyBrown{188, 143, 143};
constexpr Color Color::kRoyalBlue{65, 105, 225};
constexpr Color Color::kSaddleBrown{139, 69, 19};
constexpr Color Color::kSalmon{250, 128, 114};
constexpr Color Color::kSandyBrown{244, 164, 96};
constexpr Color Color::kSeaGreen{46, 139, 87};
constexpr Color Color::kSeashell{255, 245, 238};
constexpr Color Color::kSienna{160, 82, 45};
constexpr Color Color::kSilver{192, 192, 192};
constexpr Color Color::kSkyBlue{135, 206, 235};
constexpr Color Color::kSlateBlue{106, 90, 205};
constexpr Color Color::kSlateGray{112, 128, 144};
constexpr Color Color::kSlateGrey{112, 128, 144};
constexpr Color Color::kSnow{255, 250, 250};
constexpr Color Color::kSpringGreen{0, 255, 127};
constexpr Color Color::kSteelBlue{70, 130, 180};
constexpr Color Color::kTan{210, 180, 140};
constexpr Color Color::kTeal{0, 128, 128};
constexpr Color Color::kThistle{216, 191, 216};
constexpr Color Color::kTomato{255, 99, 71};
constexpr Color Color::kTurquoise{64, 224, 208};
constexpr Color Color::kViolet{238, 130, 238};
constexpr Color Color::kWheat{245, 222, 179};
constexpr Color Color::kWhite{255, 255, 255};
constexpr Color Color::kWhiteSmoke{245, 245, 245};
constexpr Color Color::kYellow{255, 255, 0};
constexpr Color Color::kYellowGreen{154, 205, 50};
}  // namespace frc
