from . import _init__wpiutil

# autogenerated by 'semiwrap create-imports wpiutil wpiutil._wpiutil'
from ._wpiutil import (
    Color,
    Color8Bit,
    Sendable,
    SendableBuilder,
    SendableRegistry,
    TimestampSource,
    getStackTrace,
    getStackTraceDefault,
)

__all__ = [
    "Color",
    "Color8Bit",
    "Sendable",
    "SendableBuilder",
    "SendableRegistry",
    "TimestampSource",
    "getStackTrace",
    "getStackTraceDefault",
]

# Imported for side effects only
from . import _stacktrace

# Type alias
import typing

json = typing.Union[None, bool, int, float, str, typing.List, typing.Dict]
