load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_library(
    name = "wpiutil-testlib",
    hdrs = glob(["include/**"]),
    strip_include_prefix = "include",
    visibility = ["//visibility:public"],
)

cc_test(
    name = "tests",
    size = "small",
    srcs = glob(["cpp/**"]) + ["//wpiutil:generated-test-native-srcs"],
    linkstatic = True,
    tags = ["no-tsan"],  # TODO(pj.reiniger) Find problem
    deps = [
        ":wpiutil-testlib",
        "//thirdparty/catch2",
        "//wpiutil",
        "//wpiutil:nanopb-test-headers",
        "@wpilib_toolchains//jni",
    ],
)
