// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.

#include "wpi/filterdesigner/codegen/Export.hpp"

#include <cctype>
#include <fstream>
#include <string>
#include <string_view>
#include <system_error>
#include <utility>

#include <fmt/format.h>

#include "CodeGenLines.hpp"

namespace wpi::filterdesigner {

using detail::Join;
using detail::Lines;
using detail::PrefixLines;
using detail::SplitLines;

namespace {

Lines DoNotEditHeader() {
  return {
      "Generated by WPILib Filter Designer.",
      "DO NOT EDIT \xE2\x80\x94 regenerate via the Filter Designer tool.",
  };
}

void Append(Lines& dst, Lines&& src) {
  dst.insert(dst.end(), std::make_move_iterator(src.begin()),
             std::make_move_iterator(src.end()));
}

Lines EmitCppFile(const Sections& sections, std::string_view className,
                  const ExportSpec& spec) {
  Lines out = PrefixLines(DoNotEditHeader(), "// ");
  out.emplace_back("//");
  Append(out, PrefixLines(SplitLines(spec.description), "// "));
  out.emplace_back("");
  out.emplace_back("#pragma once");
  out.emplace_back("");
  out.emplace_back("#include <wpi/math/filter/BiquadFilter.hpp>");
  out.emplace_back("");
  out.emplace_back("namespace frc::filters {");
  out.emplace_back("");
  out.push_back(
      fmt::format("inline wpi::math::BiquadFilter {}() {{", className));
  out.emplace_back("  return wpi::math::BiquadFilter{");
  for (const Section& s : sections) {
    out.push_back(
        fmt::format("      {{{:.17g}, {:.17g}, {:.17g}, {:.17g}, {:.17g}}},",
                    s.b0, s.b1, s.b2, s.a1, s.a2));
  }
  out.emplace_back("  };");
  out.emplace_back("}");
  out.emplace_back("");
  out.emplace_back("}  // namespace frc::filters");
  return out;
}

Lines EmitJavaFile(const Sections& sections, std::string_view className,
                   const ExportSpec& spec) {
  Lines out = PrefixLines(DoNotEditHeader(), "// ");
  out.emplace_back("//");
  Append(out, PrefixLines(SplitLines(spec.description), "// "));
  out.emplace_back("");
  out.emplace_back("package frc.robot.filters;");
  out.emplace_back("");
  out.emplace_back("import org.wpilib.math.filter.BiquadFilter;");
  out.emplace_back("");
  out.push_back(fmt::format("public final class {} {{", className));
  out.emplace_back("  public static BiquadFilter create() {");
  out.emplace_back("    return new BiquadFilter(");
  for (size_t i = 0; i < sections.size(); ++i) {
    const Section& s = sections[i];
    std::string_view sep = (i + 1 < sections.size()) ? "," : "";
    out.push_back(fmt::format(
        "        new BiquadFilter.Section({:.17g}, {:.17g}, {:.17g}, {:.17g}, "
        "{:.17g}){}",
        s.b0, s.b1, s.b2, s.a1, s.a2, sep));
  }
  out.emplace_back("    );");
  out.emplace_back("  }");
  out.emplace_back("");
  out.push_back(fmt::format("  private {}() {{}}", className));
  out.emplace_back("}");
  return out;
}

Lines EmitPythonFile(const Sections& sections, std::string_view className,
                     const ExportSpec& spec) {
  std::string snake = ToSnakeCase(className);
  Lines out = PrefixLines(DoNotEditHeader(), "# ");
  out.emplace_back("#");
  Append(out, PrefixLines(SplitLines(spec.description), "# "));
  out.emplace_back("");
  out.emplace_back("from wpimath.filter import BiquadFilter");
  out.emplace_back("");
  out.emplace_back("");
  out.push_back(fmt::format("def {}() -> BiquadFilter:", snake));
  out.emplace_back("    return BiquadFilter([");
  for (const Section& s : sections) {
    out.push_back(fmt::format(
        "        BiquadFilter.Section(b0={:.17g}, b1={:.17g}, b2={:.17g}, "
        "a1={:.17g}, a2={:.17g}),",
        s.b0, s.b1, s.b2, s.a1, s.a2));
  }
  out.emplace_back("    ])");
  return out;
}

}  // namespace

bool IsValidIdentifier(std::string_view name) {
  if (name.empty()) {
    return false;
  }
  unsigned char first = static_cast<unsigned char>(name[0]);
  if (!(std::isalpha(first) || first == '_')) {
    return false;
  }
  for (size_t i = 1; i < name.size(); ++i) {
    unsigned char c = static_cast<unsigned char>(name[i]);
    if (!(std::isalnum(c) || c == '_')) {
      return false;
    }
  }
  return true;
}

std::string ToSnakeCase(std::string_view name) {
  std::string out;
  out.reserve(name.size() + 4);
  for (size_t i = 0; i < name.size(); ++i) {
    unsigned char c = static_cast<unsigned char>(name[i]);
    if (i > 0 && std::isupper(c)) {
      unsigned char prev = static_cast<unsigned char>(name[i - 1]);
      bool nextLower = i + 1 < name.size() &&
                       std::islower(static_cast<unsigned char>(name[i + 1]));
      if (std::islower(prev) || std::isdigit(prev) ||
          (std::isupper(prev) && nextLower)) {
        out.push_back('_');
      }
    }
    out.push_back(static_cast<char>(std::tolower(c)));
  }
  return out;
}

std::filesystem::path NormalizeProjectRoot(const std::filesystem::path& raw) {
  if (raw.empty()) {
    return {};
  }
  std::error_code ec;
  auto absolute = std::filesystem::absolute(raw, ec);
  if (ec) {
    return raw;
  }
  return absolute.lexically_normal();
}

std::filesystem::path ResolveExportPath(
    const std::filesystem::path& projectRoot, Language lang,
    std::string_view className) {
  std::filesystem::path root = NormalizeProjectRoot(projectRoot);
  switch (lang) {
    case Language::Java:
      return root / "src" / "main" / "java" / "frc" / "robot" / "filters" /
             (std::string{className} + ".java");
    case Language::Cpp:
      return root / "src" / "main" / "include" / "filters" /
             (std::string{className} + ".h");
    case Language::Python:
      return root / "filters" / (ToSnakeCase(className) + ".py");
  }
  return {};
}

std::string BuildExportFileContents(const Sections& sections, Language lang,
                                    std::string_view className,
                                    const ExportSpec& spec) {
  if (sections.empty()) {
    return {};
  }
  switch (lang) {
    case Language::Cpp:
      return Join(EmitCppFile(sections, className, spec));
    case Language::Java:
      return Join(EmitJavaFile(sections, className, spec));
    case Language::Python:
      return Join(EmitPythonFile(sections, className, spec));
  }
  return {};
}

ExportResult ExportFilter(const Sections& sections, Language lang,
                          std::string_view className,
                          const std::filesystem::path& projectRoot,
                          const ExportSpec& spec) {
  ExportResult result;
  if (sections.empty()) {
    result.message = "No sections to export.";
    return result;
  }
  if (!IsValidIdentifier(className)) {
    result.message = "Invalid class name.";
    return result;
  }
  if (projectRoot.empty()) {
    result.message = "Project root is empty.";
    return result;
  }

  std::string contents =
      BuildExportFileContents(sections, lang, className, spec);
  if (contents.empty()) {
    result.message = "Failed to build file contents.";
    return result;
  }

  std::filesystem::path target =
      ResolveExportPath(projectRoot, lang, className);
  std::error_code ec;
  std::filesystem::create_directories(target.parent_path(), ec);
  if (ec) {
    result.message = "Failed to create directory: " + ec.message();
    return result;
  }

  std::ofstream f(target, std::ios::binary | std::ios::trunc);
  if (!f) {
    result.message = "Failed to open file for write: " + target.string();
    return result;
  }
  f.write(contents.data(), static_cast<std::streamsize>(contents.size()));
  f.close();
  if (!f) {
    result.message = "Failed to write file: " + target.string();
    return result;
  }

  result.ok = true;
  result.writtenPath = std::move(target);
  result.message = "Wrote " + result.writtenPath.string();
  return result;
}

}  // namespace wpi::filterdesigner
