// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.

// Code generated by protocol buffer compiler. Do not edit!
package edu.wpi.first.wpilibj.commandsv3.proto;

import us.hebi.quickbuf.Descriptors;
import us.hebi.quickbuf.ProtoUtil;
import us.hebi.quickbuf.RepeatedByte;

public final class Scheduler {
  private static final RepeatedByte descriptorData =
      ProtoUtil.decodeBase64(
          1691,
          "Ciljb21tYW5kc3YzL3NyYy9tYWluL3Byb3RvL3NjaGVkdWxlci5wcm90bxIJd3BpLnByb3RvIjEKG1By"
              + "b3RvYnVmUmVxdWlyZWFibGVSZXNvdXJjZRISCgRuYW1lGAEgASgJUgRuYW1lIroBCg9Qcm90b2J1ZkNv"
              + "bW1hbmQSDgoCaWQYASABKA1SAmlkEhsKCXBhcmVudF9pZBgCIAEoDVIIcGFyZW50SWQSEgoEbmFtZRgD"
              + "IAEoCVIEbmFtZRIaCghwcmlvcml0eRgEIAEoBVIIcHJpb3JpdHkSSgoMcmVxdWlyZW1lbnRzGAUgAygL"
              + "MiYud3BpLnByb3RvLlByb3RvYnVmUmVxdWlyZWFibGVSZXNvdXJjZVIMcmVxdWlyZW1lbnRzIp8BChFQ"
              + "cm90b2J1ZlNjaGVkdWxlchJDCg9xdWV1ZWRfY29tbWFuZHMYASADKAsyGi53cGkucHJvdG8uUHJvdG9i"
              + "dWZDb21tYW5kUg5xdWV1ZWRDb21tYW5kcxJFChBydW5uaW5nX2NvbW1hbmRzGAIgAygLMhoud3BpLnBy"
              + "b3RvLlByb3RvYnVmQ29tbWFuZFIPcnVubmluZ0NvbW1hbmRzQioKJmVkdS53cGkuZmlyc3Qud3BpbGli"
              + "ai5jb21tYW5kc3YzLnByb3RvUAFKnAkKBhIEAAAiAQoICgEMEgMAABIKCAoBAhIDAgASCggKAQgSAwQA"
              + "PwoJCgIIARIDBAA/CggKAQgSAwUAIgoJCgIIChIDBQAiCrICCgIEABIEEAASATKlAgogTk9URTogYWxs"
              + "b2NhdGlvbj1sYXp5bXNnIGlzIHJlcXVpcmVkIHdoZW4gZ2VuZXJhdGluZyB0aGUgSmF2YSBjbGFzc2Vz"
              + "IGZvciB0aGlzIGZpbGUsCiAgICAgICBkdWUgdG8gdGhlIHJlY3Vyc2l2ZSBQcm90b2J1ZkNvbW1hbmQg"
              + "c2NoZW1hCgphbGx3cGlsaWIgJCBwcm90b2MtcXVpY2tidWYgXAotLXF1aWNrYnVmX291dD1hbGxvY2F0"
              + "aW9uPWxhenltc2csZ2VuX2Rlc2NyaXB0b3JzPXRydWU6Y29tbWFuZHN2My9zcmMvbWFpbi9qYXZhIFwK"
              + "Y29tbWFuZHN2My9zcmMvbWFpbi9wcm90by9zY2hlZHVsZXIucHJvdG8KCgoKAwQAARIDEAgjCgsKBAQA"
              + "AgASAxECEgoMCgUEAAIABRIDEQIICgwKBQQAAgABEgMRCQ0KDAoFBAACAAMSAxEQEQoKCgIEARIEFAAa"
              + "AQoKCgMEAQESAxQIFwoLCgQEAQIAEgMVAhAKDAoFBAECAAUSAxUCCAoMCgUEAQIAARIDFQkLCgwKBQQB"
              + "AgADEgMVDg8KCwoEBAECARIDFgIXCgwKBQQBAgEFEgMWAggKDAoFBAECAQESAxYJEgoMCgUEAQIBAxID"
              + "FhUWCgsKBAQBAgISAxcCEgoMCgUEAQICBRIDFwIICgwKBQQBAgIBEgMXCQ0KDAoFBAECAgMSAxcQEQoL"
              + "CgQEAQIDEgMYAhUKDAoFBAECAwUSAxgCBwoMCgUEAQIDARIDGAgQCgwKBQQBAgMDEgMYExQKCwoEBAEC",
          "BBIDGQI4CgwKBQQBAgQEEgMZAgoKDAoFBAECBAYSAxkLJgoMCgUEAQIEARIDGSczCgwKBQQBAgQDEgMZ"
              + "NjcKCgoCBAISBBwAIgEKCgoDBAIBEgMcCBkKjQIKBAQCAgASAyACLxr/ASBOb3RlOiBjb21tYW5kcyBh"
              + "cmUgZ2VuZXJhbGx5IHF1ZXVlZCBieSB0cmlnZ2Vycywgd2hpY2ggb2NjdXJzIGltbWVkaWF0ZWx5IGJl"
              + "Zm9yZSB0aGV5IGFyZQogcHJvbW90ZWQgYW5kIHN0YXJ0IHJ1bm5pbmcuIEVudHJpZXMgd2lsbCBvbmx5"
              + "IGFwcGVhciBoZXJlIHdoZW4gc2VyaWFsaXppbmcgYSBzY2hlZHVsZXIKIF9hZnRlcl8gbWFudWFsbHkg"
              + "c2NoZWR1bGluZyBhIGNvbW1hbmQgYnV0IF9iZWZvcmVfIGNhbGxpbmcgc2NoZWR1bGVyLnJ1bigpCgoM"
              + "CgUEAgIABBIDIAIKCgwKBQQCAgAGEgMgCxoKDAoFBAICAAESAyAbKgoMCgUEAgIAAxIDIC0uCgsKBAQC"
              + "AgESAyECMAoMCgUEAgIBBBIDIQIKCgwKBQQCAgEGEgMhCxoKDAoFBAICAQESAyEbKwoMCgUEAgIBAxID"
              + "IS4vYgZwcm90bzM=");

  static final Descriptors.FileDescriptor descriptor =
      Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
          "commandsv3/src/main/proto/scheduler.proto", "wpi.proto", descriptorData);

  static final Descriptors.Descriptor wpi_proto_ProtobufRequireableResource_descriptor =
      descriptor.internalContainedType(
          56, 49, "ProtobufRequireableResource", "wpi.proto.ProtobufRequireableResource");

  static final Descriptors.Descriptor wpi_proto_ProtobufCommand_descriptor =
      descriptor.internalContainedType(108, 186, "ProtobufCommand", "wpi.proto.ProtobufCommand");

  static final Descriptors.Descriptor wpi_proto_ProtobufScheduler_descriptor =
      descriptor.internalContainedType(
          297, 159, "ProtobufScheduler", "wpi.proto.ProtobufScheduler");

  /**
   * @return this proto file's descriptor.
   */
  public static Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }
}
