load("@allwpilib_pip_deps//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_library")
load("//robotpyExamples:project.bzl", "robotpy_project")

py_library(
    name = "vision",
    srcs = ["vision.py"],
    deps = [
        # "//cscore:robotpy-cscore",
        "//ntcore:pyntcore",
        requirement("numpy"),
        requirement("opencv-python"),
    ],
)

robotpy_project(
    name = "HttpCamera",
    srcs = ["robot.py"],
    data = [":vision"],
    main = "robot.py",
    deps = [
    ],
)
