/*----------------------------------------------------------------------------*/
/* Copyright (c) 2008-2018 FIRST. All Rights Reserved.                        */
/* Open Source Software - may be modified and shared by FRC teams. The code   */
/* must be accompanied by the FIRST BSD license file in the root directory of */
/* the project.                                                               */
/*----------------------------------------------------------------------------*/

#pragma once

/*
 * The corresponding WPILibVersion.cpp file is autogenerated by the build
 * system. If it does not exist, make sure that you run a build.
 */
extern const char* GetWPILibVersion();
