load("//shared/bazel/rules:java_rules.bzl", "wpilib_java_junit5_test")

wpilib_java_junit5_test(
    name = "java",
    srcs = glob(["**/*.java"]),
    deps = [
        "//drivers:drivers-java",
        "//hal:hal-java",
        "//ntcore:ntcore-java",
        "//telemetry:telemetry-java",
        "//tunables:tunables-java",
        "//wpilibj:wpilibj-java",
        "//wpimath:wpimath-java",
        "//wpiunits:wpiunits-java",
        "//wpiutil:wpiutil-java",
    ],
)
