load("@rules_cc//cc:cc_test.bzl", "cc_test")
load("//shared/bazel/rules:imgui_test.bzl", "wpilib_imgui_cc_test")

cc_test(
    name = "tests",
    size = "small",
    srcs = glob(
        ["**/*.cpp"],
        exclude = ["imgui/**"],
    ),
    tags = [
        "no-asan",
        "wpi-cpp-gui",
    ],
    deps = [
        "//simulation/halsim_gui",
        "//thirdparty/catch2",
    ],
)

wpilib_imgui_cc_test(
    name = "halsim_gui-imgui-test",
    size = "small",
    srcs = [
        "//simulation/halsim_gui:main-native-srcs",
    ] + glob(["imgui/**"]),
    linkopts = [
        "-lm",
    ],
    tags = [
        "no-asan",
    ],
    deps = [
        "//glass:glassnt_for_tests",
        "//hal:wpiHal",
        "//simulation/halsim_gui:headers",
    ],
)
