# THIS FILE WAS AUTO-GENERATED BY ./commandsv2/generate_hids.py. DO NOT MODIFY

from typing import Optional

from wpilib import EventLoop, Switch2ProController

from .commandgenerichid import CommandGenericHID
from .trigger import Trigger


def _enum_value(value) -> int:
    try:
        return int(value)
    except TypeError:
        return value.value


class CommandSwitch2ProController:
    """
    A version of :class:`wpilib.Switch2ProController` with :class:`.Trigger` factories for command-based.
    """

    _hid: CommandGenericHID
    _controller: Switch2ProController

    def __init__(self, port: int):
        """
        Construct an instance of a controller.

        :param port: The port index on the Driver Station that the controller is plugged into.
        """
        self._hid = CommandGenericHID.getCommandGenericHID(port)
        self._controller = Switch2ProController(self._hid.getHID())

    def __getattr__(self, name: str):
        return getattr(self._hid, name)

    def getHID(self) -> CommandGenericHID:
        """
        Get the underlying CommandGenericHID object.

        :returns: the wrapped CommandGenericHID object
        """
        return self._hid

    def getController(self) -> Switch2ProController:
        """
        Get the wrapped controller object.

        :returns: the wrapped controller object
        """
        return self._controller

    def b(self, loop: Optional[EventLoop] = None) -> Trigger:
        """
        Constructs a Trigger instance around the B button's digital signal.

        :param loop: the event loop instance to attach the Trigger to, defaults
                     to :func:`commands2.CommandScheduler.getDefaultButtonLoop`

        :returns: a Trigger instance representing the B button's digital signal
                  attached to the given loop.
        """
        return self._hid.button(
            _enum_value(Switch2ProController.Button.B), loop
        )

    def a(self, loop: Optional[EventLoop] = None) -> Trigger:
        """
        Constructs a Trigger instance around the A button's digital signal.

        :param loop: the event loop instance to attach the Trigger to, defaults
                     to :func:`commands2.CommandScheduler.getDefaultButtonLoop`

        :returns: a Trigger instance representing the A button's digital signal
                  attached to the given loop.
        """
        return self._hid.button(
            _enum_value(Switch2ProController.Button.A), loop
        )

    def y(self, loop: Optional[EventLoop] = None) -> Trigger:
        """
        Constructs a Trigger instance around the Y button's digital signal.

        :param loop: the event loop instance to attach the Trigger to, defaults
                     to :func:`commands2.CommandScheduler.getDefaultButtonLoop`

        :returns: a Trigger instance representing the Y button's digital signal
                  attached to the given loop.
        """
        return self._hid.button(
            _enum_value(Switch2ProController.Button.Y), loop
        )

    def x(self, loop: Optional[EventLoop] = None) -> Trigger:
        """
        Constructs a Trigger instance around the X button's digital signal.

        :param loop: the event loop instance to attach the Trigger to, defaults
                     to :func:`commands2.CommandScheduler.getDefaultButtonLoop`

        :returns: a Trigger instance representing the X button's digital signal
                  attached to the given loop.
        """
        return self._hid.button(
            _enum_value(Switch2ProController.Button.X), loop
        )

    def minus(self, loop: Optional[EventLoop] = None) -> Trigger:
        """
        Constructs a Trigger instance around the Minus button's digital signal.

        :param loop: the event loop instance to attach the Trigger to, defaults
                     to :func:`commands2.CommandScheduler.getDefaultButtonLoop`

        :returns: a Trigger instance representing the Minus button's digital signal
                  attached to the given loop.
        """
        return self._hid.button(
            _enum_value(Switch2ProController.Button.MINUS), loop
        )

    def home(self, loop: Optional[EventLoop] = None) -> Trigger:
        """
        Constructs a Trigger instance around the Home button's digital signal.

        :param loop: the event loop instance to attach the Trigger to, defaults
                     to :func:`commands2.CommandScheduler.getDefaultButtonLoop`

        :returns: a Trigger instance representing the Home button's digital signal
                  attached to the given loop.
        """
        return self._hid.button(
            _enum_value(Switch2ProController.Button.HOME), loop
        )

    def plus(self, loop: Optional[EventLoop] = None) -> Trigger:
        """
        Constructs a Trigger instance around the Plus button's digital signal.

        :param loop: the event loop instance to attach the Trigger to, defaults
                     to :func:`commands2.CommandScheduler.getDefaultButtonLoop`

        :returns: a Trigger instance representing the Plus button's digital signal
                  attached to the given loop.
        """
        return self._hid.button(
            _enum_value(Switch2ProController.Button.PLUS), loop
        )

    def leftStick(self, loop: Optional[EventLoop] = None) -> Trigger:
        """
        Constructs a Trigger instance around the Left Stick button's digital signal.

        :param loop: the event loop instance to attach the Trigger to, defaults
                     to :func:`commands2.CommandScheduler.getDefaultButtonLoop`

        :returns: a Trigger instance representing the Left Stick button's digital signal
                  attached to the given loop.
        """
        return self._hid.button(
            _enum_value(Switch2ProController.Button.LEFT_STICK), loop
        )

    def rightStick(self, loop: Optional[EventLoop] = None) -> Trigger:
        """
        Constructs a Trigger instance around the Right Stick button's digital signal.

        :param loop: the event loop instance to attach the Trigger to, defaults
                     to :func:`commands2.CommandScheduler.getDefaultButtonLoop`

        :returns: a Trigger instance representing the Right Stick button's digital signal
                  attached to the given loop.
        """
        return self._hid.button(
            _enum_value(Switch2ProController.Button.RIGHT_STICK), loop
        )

    def L(self, loop: Optional[EventLoop] = None) -> Trigger:
        """
        Constructs a Trigger instance around the L button's digital signal.

        :param loop: the event loop instance to attach the Trigger to, defaults
                     to :func:`commands2.CommandScheduler.getDefaultButtonLoop`

        :returns: a Trigger instance representing the L button's digital signal
                  attached to the given loop.
        """
        return self._hid.button(
            _enum_value(Switch2ProController.Button.L), loop
        )

    def R(self, loop: Optional[EventLoop] = None) -> Trigger:
        """
        Constructs a Trigger instance around the R button's digital signal.

        :param loop: the event loop instance to attach the Trigger to, defaults
                     to :func:`commands2.CommandScheduler.getDefaultButtonLoop`

        :returns: a Trigger instance representing the R button's digital signal
                  attached to the given loop.
        """
        return self._hid.button(
            _enum_value(Switch2ProController.Button.R), loop
        )

    def dpadUp(self, loop: Optional[EventLoop] = None) -> Trigger:
        """
        Constructs a Trigger instance around the Dpad Up button's digital signal.

        :param loop: the event loop instance to attach the Trigger to, defaults
                     to :func:`commands2.CommandScheduler.getDefaultButtonLoop`

        :returns: a Trigger instance representing the Dpad Up button's digital signal
                  attached to the given loop.
        """
        return self._hid.button(
            _enum_value(Switch2ProController.Button.DPAD_UP), loop
        )

    def dpadDown(self, loop: Optional[EventLoop] = None) -> Trigger:
        """
        Constructs a Trigger instance around the Dpad Down button's digital signal.

        :param loop: the event loop instance to attach the Trigger to, defaults
                     to :func:`commands2.CommandScheduler.getDefaultButtonLoop`

        :returns: a Trigger instance representing the Dpad Down button's digital signal
                  attached to the given loop.
        """
        return self._hid.button(
            _enum_value(Switch2ProController.Button.DPAD_DOWN), loop
        )

    def dpadLeft(self, loop: Optional[EventLoop] = None) -> Trigger:
        """
        Constructs a Trigger instance around the Dpad Left button's digital signal.

        :param loop: the event loop instance to attach the Trigger to, defaults
                     to :func:`commands2.CommandScheduler.getDefaultButtonLoop`

        :returns: a Trigger instance representing the Dpad Left button's digital signal
                  attached to the given loop.
        """
        return self._hid.button(
            _enum_value(Switch2ProController.Button.DPAD_LEFT), loop
        )

    def dpadRight(self, loop: Optional[EventLoop] = None) -> Trigger:
        """
        Constructs a Trigger instance around the Dpad Right button's digital signal.

        :param loop: the event loop instance to attach the Trigger to, defaults
                     to :func:`commands2.CommandScheduler.getDefaultButtonLoop`

        :returns: a Trigger instance representing the Dpad Right button's digital signal
                  attached to the given loop.
        """
        return self._hid.button(
            _enum_value(Switch2ProController.Button.DPAD_RIGHT), loop
        )

    def capture(self, loop: Optional[EventLoop] = None) -> Trigger:
        """
        Constructs a Trigger instance around the Capture button's digital signal.

        :param loop: the event loop instance to attach the Trigger to, defaults
                     to :func:`commands2.CommandScheduler.getDefaultButtonLoop`

        :returns: a Trigger instance representing the Capture button's digital signal
                  attached to the given loop.
        """
        return self._hid.button(
            _enum_value(Switch2ProController.Button.CAPTURE), loop
        )

    def GR(self, loop: Optional[EventLoop] = None) -> Trigger:
        """
        Constructs a Trigger instance around the GR button's digital signal.

        :param loop: the event loop instance to attach the Trigger to, defaults
                     to :func:`commands2.CommandScheduler.getDefaultButtonLoop`

        :returns: a Trigger instance representing the GR button's digital signal
                  attached to the given loop.
        """
        return self._hid.button(
            _enum_value(Switch2ProController.Button.GR), loop
        )

    def GL(self, loop: Optional[EventLoop] = None) -> Trigger:
        """
        Constructs a Trigger instance around the GL button's digital signal.

        :param loop: the event loop instance to attach the Trigger to, defaults
                     to :func:`commands2.CommandScheduler.getDefaultButtonLoop`

        :returns: a Trigger instance representing the GL button's digital signal
                  attached to the given loop.
        """
        return self._hid.button(
            _enum_value(Switch2ProController.Button.GL), loop
        )

    def C(self, loop: Optional[EventLoop] = None) -> Trigger:
        """
        Constructs a Trigger instance around the C button's digital signal.

        :param loop: the event loop instance to attach the Trigger to, defaults
                     to :func:`commands2.CommandScheduler.getDefaultButtonLoop`

        :returns: a Trigger instance representing the C button's digital signal
                  attached to the given loop.
        """
        return self._hid.button(
            _enum_value(Switch2ProController.Button.C), loop
        )

    def ZL(
        self,
        threshold: float = 0.5,
        loop: Optional[EventLoop] = None,
    ) -> Trigger:
        """
        Constructs a Trigger instance around the ZL axis value. The returned
        Trigger will be true when the axis value is greater than ``threshold``.

        :param threshold: the minimum axis value for the returned Trigger to be true. This value
                          should be in the range [0, 1] where 0 is the unpressed state of the axis.
        :param loop: the event loop instance to attach the Trigger to, defaults
                     to :func:`commands2.CommandScheduler.getDefaultButtonLoop`

        :returns: a Trigger instance that is true when the ZL axis exceeds the
                  provided threshold, attached to the given event loop.
        """
        return self._hid.axisGreaterThan(
            _enum_value(Switch2ProController.Axis.ZL),
            threshold,
            loop,
        )

    def ZR(
        self,
        threshold: float = 0.5,
        loop: Optional[EventLoop] = None,
    ) -> Trigger:
        """
        Constructs a Trigger instance around the ZR axis value. The returned
        Trigger will be true when the axis value is greater than ``threshold``.

        :param threshold: the minimum axis value for the returned Trigger to be true. This value
                          should be in the range [0, 1] where 0 is the unpressed state of the axis.
        :param loop: the event loop instance to attach the Trigger to, defaults
                     to :func:`commands2.CommandScheduler.getDefaultButtonLoop`

        :returns: a Trigger instance that is true when the ZR axis exceeds the
                  provided threshold, attached to the given event loop.
        """
        return self._hid.axisGreaterThan(
            _enum_value(Switch2ProController.Axis.ZR),
            threshold,
            loop,
        )

    def getLeftX(self) -> float:
        """
        Get the Left X value of the controller.

        :returns: the axis value.
        """
        return self._controller.getLeftX()

    def getLeftY(self) -> float:
        """
        Get the Left Y value of the controller.

        :returns: the axis value.
        """
        return self._controller.getLeftY()

    def getRightX(self) -> float:
        """
        Get the Right X value of the controller.

        :returns: the axis value.
        """
        return self._controller.getRightX()

    def getRightY(self) -> float:
        """
        Get the Right Y value of the controller.

        :returns: the axis value.
        """
        return self._controller.getRightY()

    def getZL(self) -> float:
        """
        Get the ZL value of the controller.

        :returns: the axis value.
        """
        return self._controller.getZL()

    def getZR(self) -> float:
        """
        Get the ZR value of the controller.

        :returns: the axis value.
        """
        return self._controller.getZR()
