# THIS FILE WAS AUTO-GENERATED BY ./commandsv2/generate_hids.py. DO NOT MODIFY

from typing import Optional

from wpilib import EventLoop, DualSenseController

from .commandgenerichid import CommandGenericHID
from .trigger import Trigger


class CommandDualSenseController:
    """
    A version of :class:`wpilib.DualSenseController` with :class:`.Trigger` factories for command-based.
    """

    _hid: CommandGenericHID
    _controller: DualSenseController

    def __init__(self, port: int):
        """
        Construct an instance of a controller.

        :param port: The port index on the Driver Station that the controller is plugged into.
        """
        self._hid = CommandGenericHID.getCommandGenericHID(port)
        self._controller = DualSenseController(self._hid.getHID())

    def getHID(self) -> CommandGenericHID:
        """
        Get the underlying CommandGenericHID object.

        :returns: the wrapped CommandGenericHID object
        """
        return self._hid

    def getController(self) -> DualSenseController:
        """
        Get the wrapped controller object.

        :returns: the wrapped controller object
        """
        return self._controller

    def button(
        self,
        button: DualSenseController.Button,
        loop: Optional[EventLoop] = None,
    ) -> Trigger:
        """
        Constructs an event instance around this button's digital signal.

        :param button: the :class:`wpilib.DualSenseController.Button` to read
        :param loop: the event loop instance to attach the event to
        """
        return self._hid.button(button.value, loop)

    def cross(self, loop: Optional[EventLoop] = None) -> Trigger:
        """
        Constructs a Trigger instance around the Cross button's digital signal.

        :param loop: the event loop instance to attach the Trigger to, defaults
                     to :func:`commands2.CommandScheduler.getDefaultButtonLoop`

        :returns: a Trigger instance representing the Cross button's digital signal
                  attached to the given loop.
        """
        return self.button(DualSenseController.Button.CROSS, loop)

    def circle(self, loop: Optional[EventLoop] = None) -> Trigger:
        """
        Constructs a Trigger instance around the Circle button's digital signal.

        :param loop: the event loop instance to attach the Trigger to, defaults
                     to :func:`commands2.CommandScheduler.getDefaultButtonLoop`

        :returns: a Trigger instance representing the Circle button's digital signal
                  attached to the given loop.
        """
        return self.button(DualSenseController.Button.CIRCLE, loop)

    def square(self, loop: Optional[EventLoop] = None) -> Trigger:
        """
        Constructs a Trigger instance around the Square button's digital signal.

        :param loop: the event loop instance to attach the Trigger to, defaults
                     to :func:`commands2.CommandScheduler.getDefaultButtonLoop`

        :returns: a Trigger instance representing the Square button's digital signal
                  attached to the given loop.
        """
        return self.button(DualSenseController.Button.SQUARE, loop)

    def triangle(self, loop: Optional[EventLoop] = None) -> Trigger:
        """
        Constructs a Trigger instance around the Triangle button's digital signal.

        :param loop: the event loop instance to attach the Trigger to, defaults
                     to :func:`commands2.CommandScheduler.getDefaultButtonLoop`

        :returns: a Trigger instance representing the Triangle button's digital signal
                  attached to the given loop.
        """
        return self.button(DualSenseController.Button.TRIANGLE, loop)

    def create(self, loop: Optional[EventLoop] = None) -> Trigger:
        """
        Constructs a Trigger instance around the Create button's digital signal.

        :param loop: the event loop instance to attach the Trigger to, defaults
                     to :func:`commands2.CommandScheduler.getDefaultButtonLoop`

        :returns: a Trigger instance representing the Create button's digital signal
                  attached to the given loop.
        """
        return self.button(DualSenseController.Button.CREATE, loop)

    def PS(self, loop: Optional[EventLoop] = None) -> Trigger:
        """
        Constructs a Trigger instance around the PS button's digital signal.

        :param loop: the event loop instance to attach the Trigger to, defaults
                     to :func:`commands2.CommandScheduler.getDefaultButtonLoop`

        :returns: a Trigger instance representing the PS button's digital signal
                  attached to the given loop.
        """
        return self.button(DualSenseController.Button.PS, loop)

    def options(self, loop: Optional[EventLoop] = None) -> Trigger:
        """
        Constructs a Trigger instance around the Options button's digital signal.

        :param loop: the event loop instance to attach the Trigger to, defaults
                     to :func:`commands2.CommandScheduler.getDefaultButtonLoop`

        :returns: a Trigger instance representing the Options button's digital signal
                  attached to the given loop.
        """
        return self.button(DualSenseController.Button.OPTIONS, loop)

    def L3(self, loop: Optional[EventLoop] = None) -> Trigger:
        """
        Constructs a Trigger instance around the L 3 button's digital signal.

        :param loop: the event loop instance to attach the Trigger to, defaults
                     to :func:`commands2.CommandScheduler.getDefaultButtonLoop`

        :returns: a Trigger instance representing the L 3 button's digital signal
                  attached to the given loop.
        """
        return self.button(DualSenseController.Button.L3, loop)

    def R3(self, loop: Optional[EventLoop] = None) -> Trigger:
        """
        Constructs a Trigger instance around the R 3 button's digital signal.

        :param loop: the event loop instance to attach the Trigger to, defaults
                     to :func:`commands2.CommandScheduler.getDefaultButtonLoop`

        :returns: a Trigger instance representing the R 3 button's digital signal
                  attached to the given loop.
        """
        return self.button(DualSenseController.Button.R3, loop)

    def L1(self, loop: Optional[EventLoop] = None) -> Trigger:
        """
        Constructs a Trigger instance around the L 1 button's digital signal.

        :param loop: the event loop instance to attach the Trigger to, defaults
                     to :func:`commands2.CommandScheduler.getDefaultButtonLoop`

        :returns: a Trigger instance representing the L 1 button's digital signal
                  attached to the given loop.
        """
        return self.button(DualSenseController.Button.L1, loop)

    def R1(self, loop: Optional[EventLoop] = None) -> Trigger:
        """
        Constructs a Trigger instance around the R 1 button's digital signal.

        :param loop: the event loop instance to attach the Trigger to, defaults
                     to :func:`commands2.CommandScheduler.getDefaultButtonLoop`

        :returns: a Trigger instance representing the R 1 button's digital signal
                  attached to the given loop.
        """
        return self.button(DualSenseController.Button.R1, loop)

    def dpadUp(self, loop: Optional[EventLoop] = None) -> Trigger:
        """
        Constructs a Trigger instance around the Dpad Up button's digital signal.

        :param loop: the event loop instance to attach the Trigger to, defaults
                     to :func:`commands2.CommandScheduler.getDefaultButtonLoop`

        :returns: a Trigger instance representing the Dpad Up button's digital signal
                  attached to the given loop.
        """
        return self.button(DualSenseController.Button.DPAD_UP, loop)

    def dpadDown(self, loop: Optional[EventLoop] = None) -> Trigger:
        """
        Constructs a Trigger instance around the Dpad Down button's digital signal.

        :param loop: the event loop instance to attach the Trigger to, defaults
                     to :func:`commands2.CommandScheduler.getDefaultButtonLoop`

        :returns: a Trigger instance representing the Dpad Down button's digital signal
                  attached to the given loop.
        """
        return self.button(DualSenseController.Button.DPAD_DOWN, loop)

    def dpadLeft(self, loop: Optional[EventLoop] = None) -> Trigger:
        """
        Constructs a Trigger instance around the Dpad Left button's digital signal.

        :param loop: the event loop instance to attach the Trigger to, defaults
                     to :func:`commands2.CommandScheduler.getDefaultButtonLoop`

        :returns: a Trigger instance representing the Dpad Left button's digital signal
                  attached to the given loop.
        """
        return self.button(DualSenseController.Button.DPAD_LEFT, loop)

    def dpadRight(self, loop: Optional[EventLoop] = None) -> Trigger:
        """
        Constructs a Trigger instance around the Dpad Right button's digital signal.

        :param loop: the event loop instance to attach the Trigger to, defaults
                     to :func:`commands2.CommandScheduler.getDefaultButtonLoop`

        :returns: a Trigger instance representing the Dpad Right button's digital signal
                  attached to the given loop.
        """
        return self.button(DualSenseController.Button.DPAD_RIGHT, loop)

    def microphone(self, loop: Optional[EventLoop] = None) -> Trigger:
        """
        Constructs a Trigger instance around the Microphone button's digital signal.

        :param loop: the event loop instance to attach the Trigger to, defaults
                     to :func:`commands2.CommandScheduler.getDefaultButtonLoop`

        :returns: a Trigger instance representing the Microphone button's digital signal
                  attached to the given loop.
        """
        return self.button(DualSenseController.Button.MICROPHONE, loop)

    def touchpad(self, loop: Optional[EventLoop] = None) -> Trigger:
        """
        Constructs a Trigger instance around the Touchpad button's digital signal.

        :param loop: the event loop instance to attach the Trigger to, defaults
                     to :func:`commands2.CommandScheduler.getDefaultButtonLoop`

        :returns: a Trigger instance representing the Touchpad button's digital signal
                  attached to the given loop.
        """
        return self.button(DualSenseController.Button.TOUCHPAD, loop)

    def L2(
        self,
        threshold: float = 0.5,
        loop: Optional[EventLoop] = None,
    ) -> Trigger:
        """
        Constructs a Trigger instance around the L 2 axis value. The returned
        Trigger will be true when the axis value is greater than ``threshold``.

        :param threshold: the minimum axis value for the returned Trigger to be true. This value
                          should be in the range [0, 1] where 0 is the unpressed state of the axis.
        :param loop: the event loop instance to attach the Trigger to, defaults
                     to :func:`commands2.CommandScheduler.getDefaultButtonLoop`

        :returns: a Trigger instance that is true when the L 2 axis exceeds the
                  provided threshold, attached to the given event loop.
        """
        return self.axisGreaterThan(
            DualSenseController.Axis.L2,
            threshold,
            loop,
        )

    def R2(
        self,
        threshold: float = 0.5,
        loop: Optional[EventLoop] = None,
    ) -> Trigger:
        """
        Constructs a Trigger instance around the R 2 axis value. The returned
        Trigger will be true when the axis value is greater than ``threshold``.

        :param threshold: the minimum axis value for the returned Trigger to be true. This value
                          should be in the range [0, 1] where 0 is the unpressed state of the axis.
        :param loop: the event loop instance to attach the Trigger to, defaults
                     to :func:`commands2.CommandScheduler.getDefaultButtonLoop`

        :returns: a Trigger instance that is true when the R 2 axis exceeds the
                  provided threshold, attached to the given event loop.
        """
        return self.axisGreaterThan(
            DualSenseController.Axis.R2,
            threshold,
            loop,
        )

    def axisLessThan(
        self,
        axis: DualSenseController.Axis,
        threshold: float,
        loop: Optional[EventLoop] = None,
    ) -> Trigger:
        """
        Constructs a Trigger instance that is true when the axis value is less than
        ``threshold``, attached to the given loop.

        :param axis: the :class:`wpilib.DualSenseController.Axis` to read
        :param threshold: the value below which this Trigger should return true.
        :param loop: the event loop instance to attach the Trigger to

        :returns: a Trigger instance that is true when the axis value is less than
                  the provided threshold.
        """
        return self._hid.axisLessThan(axis.value, threshold, loop)

    def axisGreaterThan(
        self,
        axis: DualSenseController.Axis,
        threshold: float,
        loop: Optional[EventLoop] = None,
    ) -> Trigger:
        """
        Constructs a Trigger instance that is true when the axis value is greater
        than ``threshold``, attached to the given loop.

        :param axis: the :class:`wpilib.DualSenseController.Axis` to read
        :param threshold: the value above which this Trigger should return true.
        :param loop: the event loop instance to attach the Trigger to.

        :returns: a Trigger instance that is true when the axis value is greater
                  than the provided threshold.
        """
        return self._hid.axisGreaterThan(axis.value, threshold, loop)

    def axisMagnitudeGreaterThan(
        self,
        axis: DualSenseController.Axis,
        threshold: float,
        loop: Optional[EventLoop] = None,
    ) -> Trigger:
        """
        Constructs a Trigger instance that is true when the axis magnitude is
        greater than ``threshold``, attached to the given loop.

        :param axis: the :class:`wpilib.DualSenseController.Axis` to read
        :param threshold: the value above which this Trigger should return true.
        :param loop: the event loop instance to attach the Trigger to.

        :returns: a Trigger instance that is true when the axis magnitude is
                  greater than the provided threshold.
        """
        return self._hid.axisMagnitudeGreaterThan(axis.value, threshold, loop)

    def getAxis(self, axis: DualSenseController.Axis) -> float:
        """
        Get the value of the axis.

        :param axis: the :class:`wpilib.DualSenseController.Axis` to read
        """
        return self._hid.getRawAxis(axis.value)


    def getLeftX(self) -> float:
        """
        Get the Left X value of the controller.

        :returns: the axis value.
        """
        return self._controller.getLeftX()

    def getLeftY(self) -> float:
        """
        Get the Left Y value of the controller.

        :returns: the axis value.
        """
        return self._controller.getLeftY()

    def getRightX(self) -> float:
        """
        Get the Right X value of the controller.

        :returns: the axis value.
        """
        return self._controller.getRightX()

    def getRightY(self) -> float:
        """
        Get the Right Y value of the controller.

        :returns: the axis value.
        """
        return self._controller.getRightY()

    def getL2(self) -> float:
        """
        Get the L 2 value of the controller.

        :returns: the axis value.
        """
        return self._controller.getL2()

    def getR2(self) -> float:
        """
        Get the R 2 value of the controller.

        :returns: the axis value.
        """
        return self._controller.getR2()
