load("@rules_cc//cc:cc_binary.bzl", "cc_binary")

filegroup(
    name = "sources",
    srcs = ["c/Robot.c"],
    visibility = [
        "//wpilibcExamples/src/main/cpp/examples:__subpackages__",
    ],
)

cc_binary(
    name = "HAL",
    srcs = ["c/Robot.c"],
    tags = [
        "wpi-example",
    ],
    deps = [
        "//hal:wpiHal",
        # Workaround: linking C++ objects provides a weak out-of-line copy of
        # the inline HAL_ControlWord_GetRobotMode, which C needs at -O0.
        "//wpilibc",
    ],
)
