EXAMPLES_FOLDERS = [
    "arcadedrivegamepad",
    "armsimulation",
    "differentialdrivebot",
    "differentialdriveposeestimator",
    "drivedistanceoffboard",
    "dutycycleencoder",
    "elevatorexponentialprofile",
    "elevatorexponentialsimulation",
    "elevatorprofiledpid",
    "elevatorsimulation",
    "elevatortrapezoidprofile",
    "encoder",
    "gettingstarted",
    "gyro",
    "hatchbotinlined",
    "hatchbottraditional",
    "mecanumbot",
    "mecanumdrive",
    "mecanumdriveposeestimator",
    "mechanism2d",
    "rapidreactcommandbot",
    "romireference",
    "selectcommand",
    "simpledifferentialdrivesimulation",
    "statespacearm",
    "statespaceelevator",
    "statespaceflywheel",
    "statespaceflywheelsysid",
    "swervebot",
    "swervedriveposeestimator",
    "sysidroutine",
    "tankdrivegamepad",
    "unittest",
    "xrpreference",
    "xrptimed",
]

COMMANDS_V2_FOLDERS = [
    "command2",
    "emptyclass",
    "instantcommand",
    "parallelcommandgroup",
    "paralleldeadlinegroup",
    "parallelracegroup",
    "sequentialcommandgroup",
    "subsystem2",
]

SNIPPETS_FOLDERS = [
    "accelerometercollision",
    "accelerometerfilter",
    "addressableled",
    "adxlaccelerometers",
    "analogaccelerometer",
    "analogencoder",
    "analoginput",
    "analogpotentiometer",
    "apriltagsvision",
    "canpdp",
    "digitalcommunication",
    "digitalinput",
    "dutycycleencoder",
    "dutycycleinput",
    "encoder",
    "encoderdrive",
    "encoderhoming",
    "eventloop",
    "flywheelbangbangcontroller",
    "httpcamera",
    "i2ccommunication",
    "intermediatevision",
    "limitswitch",
    "motorcontrol",
    "onboardimu",
    "profiledpidfeedforward",
    "quickvision",
    "solenoid",
]

TEMPLATES_FOLDERS = [
    "commandv2",
    "commandv2skeleton",
    "educational",
    "opmode",
    "robotbaseskeleton",
    "romicommandv2",
    "romieducational",
    "romitimed",
    "timed",
    "timedskeleton",
    "timeslice",
    "timesliceskeleton",
    "xrpcommandv2",
    "xrpeducational",
    "xrptimed",
]

EXAMPLE_TESTS_FOLDERS = [
    "armsimulation",
    "elevatorsimulation",
    "unittest",
]

SNIPPET_TESTS_FOLDERS = [
    "digitalcommunication",
    "i2ccommunication",
]
