EXAMPLE_FOLDERS = {
    "arcadedrivegamepad": ["//commandsv2:commandsv2-java"],
    "armsimulation": ["//commandsv2:commandsv2-java"],
    "differentialdrivebot": ["//commandsv2:commandsv2-java"],
    "differentialdriveposeestimator": ["//commandsv2:commandsv2-java"],
    "drivedistanceoffboard": ["//commandsv2:commandsv2-java"],
    "driverstationdisplayansi": ["//commandsv2:commandsv2-java"],
    "driverstationdisplaylines": ["//commandsv2:commandsv2-java"],
    "dsgamepadchooser": ["//commandsv2:commandsv2-java"],
    "dutycycleencoder": ["//commandsv2:commandsv2-java"],
    "elevatorexponentialprofile": ["//commandsv2:commandsv2-java"],
    "elevatorexponentialsimulation": ["//commandsv2:commandsv2-java"],
    "elevatorprofiledpid": ["//commandsv2:commandsv2-java"],
    "elevatorsimulation": ["//commandsv2:commandsv2-java"],
    "elevatortrapezoidprofile": ["//commandsv2:commandsv2-java"],
    "encoder": ["//commandsv2:commandsv2-java"],
    "expansionhubsample": ["//commandsv2:commandsv2-java"],
    "gettingstarted": ["//commandsv2:commandsv2-java"],
    "gyro": ["//commandsv2:commandsv2-java"],
    "hatchbotcmdv3": ["//commandsv3:commandsv3-java"],
    "hatchbotinlined": ["//commandsv2:commandsv2-java"],
    "hatchbottraditional": ["//commandsv2:commandsv2-java"],
    "mecanumbot": ["//commandsv2:commandsv2-java"],
    "mecanumdrive": ["//commandsv2:commandsv2-java"],
    "mecanumdriveposeestimator": ["//commandsv2:commandsv2-java"],
    "mechanism2d": ["//commandsv2:commandsv2-java"],
    "rapidreactcommandbot": ["//commandsv2:commandsv2-java"],
    "rebuiltcmdv3": ["//commandsv3:commandsv3-java"],
    "romireference": ["//commandsv2:commandsv2-java", "//romiVendordep:romiVendordep-java"],
    "simpledifferentialdrivesimulation": ["//commandsv2:commandsv2-java"],
    "statespacearm": ["//commandsv2:commandsv2-java"],
    "statespaceelevator": ["//commandsv2:commandsv2-java"],
    "statespaceflywheel": ["//commandsv2:commandsv2-java"],
    "statespaceflywheelsysid": ["//commandsv2:commandsv2-java"],
    "swervebot": ["//commandsv2:commandsv2-java"],
    "swervedriveposeestimator": ["//commandsv2:commandsv2-java"],
    "sysidroutine": ["//commandsv2:commandsv2-java"],
    "tankdrivegamepad": ["//commandsv2:commandsv2-java"],
    "unittest": ["//commandsv2:commandsv2-java"],
    "xrpreference": ["//commandsv2:commandsv2-java", "//xrpVendordep:xrpVendordep-java"],
    "xrptimed": ["//commandsv2:commandsv2-java", "//xrpVendordep:xrpVendordep-java"],
}

COMMANDS_V2_FOLDERS = {
    "command2": ["//commandsv2:commandsv2-java"],
    "emptyclass": [],
    "instantcommand": ["//commandsv2:commandsv2-java"],
    "parallelcommandgroup": ["//commandsv2:commandsv2-java"],
    "paralleldeadlinegroup": ["//commandsv2:commandsv2-java"],
    "parallelracegroup": ["//commandsv2:commandsv2-java"],
    "sequentialcommandgroup": ["//commandsv2:commandsv2-java"],
    "subsystem2": ["//commandsv2:commandsv2-java"],
}

SNIPPET_FOLDERS = {
    "accelerometercollision": [],
    "accelerometerfilter": [],
    "addressableled": [],
    "adxlaccelerometers": [],
    "analogaccelerometer": [],
    "analogencoder": [],
    "analoginput": [],
    "analogpotentiometer": [],
    "apriltagsvision": ["//cameraserver:cameraserver-java", "//cscore:cscore-java"],
    "canpdp": [],
    "differentialdrive": [],
    "digitalcommunication": [],
    "digitalinput": [],
    "dutycycleencoder": [],
    "dutycycleinput": [],
    "encoder": [],
    "encoderdrive": [],
    "encoderhoming": [],
    "eventloop": [],
    "flywheelbangbangcontroller": [],
    "httpcamera": ["//cameraserver:cameraserver-java", "//cscore:cscore-java"],
    "i2ccommunication": [],
    "intermediatevision": ["//cameraserver:cameraserver-java", "//cscore:cscore-java"],
    "limitswitch": [],
    "mecanumdrive": [],
    "motorcontrol": [],
    "onboardimu": [],
    "profiledpidfeedforward": [],
    "quickvision": ["//cameraserver:cameraserver-java", "//cscore:cscore-java"],
    "selectcommand": ["//commandsv2:commandsv2-java"],
    "solenoid": [],
}

TEMPLATE_FOLDERS = {
    "commandv2": ["//commandsv2:commandsv2-java"],
    "commandv2skeleton": ["//commandsv2:commandsv2-java"],
    "commandv3": ["//commandsv3:commandsv3-java"],
    "commandv3skeleton": ["//commandsv3:commandsv3-java"],
    "educational": ["//commandsv2:commandsv2-java"],
    "opmode": ["//commandsv2:commandsv2-java"],
    "robotbaseskeleton": ["//commandsv2:commandsv2-java"],
    "romicommandv2": ["//commandsv2:commandsv2-java", "//romiVendordep:romiVendordep-java"],
    "romieducational": ["//commandsv2:commandsv2-java", "//romiVendordep:romiVendordep-java"],
    "romitimed": ["//commandsv2:commandsv2-java", "//romiVendordep:romiVendordep-java"],
    "timed": ["//commandsv2:commandsv2-java"],
    "timedskeleton": ["//commandsv2:commandsv2-java"],
    "timeslice": ["//commandsv2:commandsv2-java"],
    "timesliceskeleton": ["//commandsv2:commandsv2-java"],
    "xrpcommandv2": ["//commandsv2:commandsv2-java", "//xrpVendordep:xrpVendordep-java"],
    "xrpeducational": ["//commandsv2:commandsv2-java", "//xrpVendordep:xrpVendordep-java"],
    "xrptimed": ["//commandsv2:commandsv2-java", "//xrpVendordep:xrpVendordep-java"],
}

EXAMPLE_TESTS_FOLDERS = {
    "armsimulation": [],
    "elevatorsimulation": [],
    "unittest": [],
}

SNIPPET_TESTS_FOLDERS = {
    "digitalcommunication": [],
    "i2ccommunication": [],
}
