if (project.hasProperty('onlylinuxsystemcore')) {
    return;
}

apply plugin: 'cpp'
apply plugin: 'google-test-test-suite'
apply from: "${rootDir}/shared/catch2.gradle"
apply plugin: 'org.wpilib.NativeUtils'
apply plugin: ExtraTasks

description = "Core library for WebSocket extensions"

ext {
    includeWpiutil = true
    includeWpinet = true
    pluginName = 'halsim_ws_core'
}

apply from: "${rootDir}/shared/config.gradle"
apply from: "${rootDir}/shared/plugins/publish.gradle"

model {
    testSuites {
        halsim_ws_coreTest(GoogleTestTestSuiteSpec) {
            testing $.components.halsim_ws_core
            sources.cpp {
                source {
                    srcDirs 'src/test/native/cpp'
                    include '**/*.cpp'
                }
            }
        }
    }

    components {
        halsim_ws_core(NativeLibrarySpec) {
            sources.cpp {
                source {
                    srcDirs = ['src/main/native/cpp']
                    includes = ["**/*.cpp"]
                }
                exportedHeaders {
                    srcDirs = ["src/main/native/include"]
                }
            }
            binaries.all {
                lib project: ':hal', library: 'hal', linkage: 'shared'
                project(':ntcore').addNtcoreDependency(it, 'shared')
                lib project: ':wpinet', library: 'wpinet', linkage: 'shared'
                lib project: ':wpiutil', library: 'wpiutil', linkage: 'shared'
            }
            appendDebugPathToBinaries(binaries)
        }
    }
    binaries {
        withType(GoogleTestTestSuiteBinarySpec) {
            lib project: ':hal', library: 'hal', linkage: 'shared'
            project(':ntcore').addNtcoreDependency(it, 'shared')
            lib project: ':wpinet', library: 'wpinet', linkage: 'shared'
            lib project: ':wpiutil', library: 'wpiutil', linkage: 'shared'
            lib library: 'halsim_ws_core', linkage: 'static'
        }
        all {
            if (it.targetPlatform.name == nativeUtils.wpi.platforms.systemcore) {
                it.buildable = false
                return
            }
        }
    }
}
