# Job for win 32.

parameters:
  pool:
    vmImage: 'windows-2019'
  preBuild: []

jobs:
- template: job-build.yml
  parameters:
    jobName: 'Windows_32_Bit'
    pool: ${{ parameters.pool }}
    container: ''
    gradleOptions: '-Xmx1024m'
    buildOptions: '-PskipPMD'
    artifactName: 'Win32'
    preBuild:
    - ${{ parameters.preBuild }}
    - powershell: |
        mkdir build
        $ProgressPreference = 'SilentlyContinue'
        wget "https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.4%2B11/OpenJDK11U-jdk_x86-32_windows_hotspot_11.0.4_11.zip" -O "build\jdk.zip"
      displayName: 'Download JDK'
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '11'
        jdkSourceOption: localDirectory
        jdkFile: 'build/jdk.zip'
        jdkDestinationDirectory: 'build/jdkinst'
        jdkArchitectureOption: x86
