load("@aos//aos:flatbuffers.bzl", "cc_static_flatbuffer")
load("@aos//aos/flatbuffers:generate.bzl", "static_flatbuffer")

# Schemas for FlatbufferToProtoTest. They are a package of their own so the
# path one uses to include another is the path its generated header is at.

static_flatbuffer(
    name = "flatbuffer_to_proto_test_fbs",
    srcs = ["flatbuffer_to_proto_test.fbs"],
    visibility = ["//aosnt:__pkg__"],
)

static_flatbuffer(
    name = "flatbuffer_to_proto_scalars_test_fbs",
    srcs = ["flatbuffer_to_proto_scalars_test.fbs"],
    visibility = ["//aosnt:__pkg__"],
)

static_flatbuffer(
    name = "flatbuffer_to_proto_spanning_test_fbs",
    srcs = ["flatbuffer_to_proto_spanning_test.fbs"],
    visibility = ["//aosnt:__pkg__"],
    deps = [":flatbuffer_to_proto_test_fbs"],
)

static_flatbuffer(
    name = "flatbuffer_to_proto_defaults_test_fbs",
    srcs = ["flatbuffer_to_proto_defaults_test.fbs"],
    visibility = ["//aosnt:__pkg__"],
)

static_flatbuffer(
    name = "flatbuffer_to_proto_arrays_test_fbs",
    srcs = ["flatbuffer_to_proto_arrays_test.fbs"],
    visibility = ["//aosnt:__pkg__"],
)

static_flatbuffer(
    name = "flatbuffer_to_proto_bad_attribute_test_fbs",
    srcs = ["flatbuffer_to_proto_bad_attribute_test.fbs"],
    visibility = ["//aosnt:__pkg__"],
)

cc_static_flatbuffer(
    name = "flatbuffer_to_proto_test_schema",
    function = "wpi::aosnt::testing::ControlDataSchema",
    target = ":flatbuffer_to_proto_test_fbs_fbs_reflection_out",
    visibility = ["//aosnt:__pkg__"],
)

cc_static_flatbuffer(
    name = "flatbuffer_to_proto_scalars_test_schema",
    function = "wpi::aosnt::testing::ScalarsSchema",
    target = ":flatbuffer_to_proto_scalars_test_fbs_fbs_reflection_out",
    visibility = ["//aosnt:__pkg__"],
)

cc_static_flatbuffer(
    name = "flatbuffer_to_proto_spanning_test_schema",
    function = "wpi::aosnt::testing::spanning::SpanningSchema",
    target = ":flatbuffer_to_proto_spanning_test_fbs_fbs_reflection_out",
    visibility = ["//aosnt:__pkg__"],
)

cc_static_flatbuffer(
    name = "flatbuffer_to_proto_bad_attribute_test_schema",
    function = "wpi::aosnt::testing::BadAttributeSchema",
    target = ":flatbuffer_to_proto_bad_attribute_test_fbs_fbs_reflection_out",
    visibility = ["//aosnt:__pkg__"],
)

cc_static_flatbuffer(
    name = "flatbuffer_to_proto_defaults_test_schema",
    function = "wpi::aosnt::testing::DefaultsSchema",
    target = ":flatbuffer_to_proto_defaults_test_fbs_fbs_reflection_out",
    visibility = ["//aosnt:__pkg__"],
)

cc_static_flatbuffer(
    name = "flatbuffer_to_proto_arrays_test_schema",
    function = "wpi::aosnt::testing::ArraysSchema",
    target = ":flatbuffer_to_proto_arrays_test_fbs_fbs_reflection_out",
    visibility = ["//aosnt:__pkg__"],
)
