//
// This file is auto-generated by wpilibj/wpilibJavaJNI/nivision/gen_java.py
// Please do not edit!
//

package com.ni.vision;

public class VisionException extends RuntimeException {

  private static final long serialVersionUID = 1L;

  public VisionException(String msg) {
    super(msg);
  }

  @Override
  public String toString() {
    return "VisionException [" + super.toString() + "]";
  }
}
