/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.wpi.first.wpilibj.hal;

public class SWIGTYPE_p_CTR_Code {
  private long swigCPtr;

  protected SWIGTYPE_p_CTR_Code(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_CTR_Code() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_CTR_Code obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

