load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_test(
    name = "glass_tests",
    size = "small",
    srcs = glob(["cpp/**"]),
    tags = [
        "wpi-cpp-gui",
    ],
    deps = [
        "//glass",
        "//thirdparty/catch2",
    ],
)

alias(
    name = "native",
    actual = ":glass_tests",
)
