ext {
    nativeName = 'cameraserver'
    devMain = 'org.wpilib.cameraserver.DevMain'
}

evaluationDependsOn(':ntcore')
evaluationDependsOn(':cscore')
evaluationDependsOn(':datalog')
evaluationDependsOn(':hal')
evaluationDependsOn(':wpilibc')
evaluationDependsOn(':wpilibj')
evaluationDependsOn(':wpimath')
evaluationDependsOn(':telemetry')
evaluationDependsOn(':tunables')

apply from: "${rootDir}/shared/javacpp/setupBuild.gradle"
apply from: "${rootDir}/shared/libmrclib.gradle"

dependencies {
    implementation project(':wpiutil')
    implementation project(':wpinet')
    implementation project(':ntcore')
    implementation project(':hal')
    api project(':cscore')
    implementation project(':datalog')
    implementation project(':wpilibj')
    implementation project(':wpimath')
    implementation project(':telemetry')
    implementation project(':tunables')
}

ext {
    sharedCvConfigs = [cameraserver    : [],
        cameraserverBase: [],
        cameraserverDev : [],
        cameraserverTest: []]
    staticCvConfigs = [:]
    useJava = true
    useCpp = true
}

apply from: "${rootDir}/shared/opencv.gradle"

nativeUtils.exportsConfigs {
    cameraserver {
    }
}

model {
    components {}
    binaries {
        all {
            if (!it.buildable || !(it instanceof NativeBinarySpec)) {
                return
            }
            project(':ntcore').addNtcoreDependency(it, 'shared')
            if (it.targetPlatform.name == nativeUtils.wpi.platforms.systemcore) {
                nativeUtils.useRequiredLibrary(it, 'mrclib')
            }
            lib project: ':hal', library: 'hal', linkage: 'shared'
            lib project: ':cscore', library: 'cscore', linkage: 'shared'
            lib project: ':wpilibc', library: 'wpilibc', linkage: 'shared'
            lib project: ':datalog', library: 'datalog', linkage: 'shared'
            lib project: ':wpinet', library: 'wpinet', linkage: 'shared'
            lib project: ':wpimath', library: 'wpimath', linkage: 'shared'
            lib project: ':telemetry', library: 'telemetry', linkage: 'shared'
            lib project: ':tunables', library: 'tunables', linkage: 'shared'
            lib project: ':wpiutil', library: 'wpiutil', linkage: 'shared'
        }
    }
    tasks {
        def c = $.components
        def found = false
        def systemArch = getCurrentArch()
        c.each {
            if (it in NativeExecutableSpec && it.name == "${nativeName}Dev") {
                it.binaries.each {
                    if (!found) {
                        def arch = it.targetPlatform.name
                        if (arch == systemArch) {
                            def filePath = it.tasks.install.installDirectory.get().toString() + File.separatorChar + 'lib'

                            found = true
                        }
                    }
                }
            }
        }
    }
}
