// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.

#pragma once

#include <functional>

#include "wpi/cs/cscore_cpp.hpp"
#include "wpi/cs/VideoEvent.hpp"

namespace wpi::cs {

/**
 * An event listener.  This calls back to a designated callback function when
 * an event matching the specified mask is generated by the library.
 */
class VideoListener {
 public:
  VideoListener() = default;

  /**
   * Create an event listener.
   *
   * @param callback Callback function
   * @param eventMask Bitmask of VideoEvent::Kind values
   * @param immediateNotify Whether callback should be immediately called with
   *        a representative set of events for the current library state.
   */
  VideoListener(std::function<void(const VideoEvent& event)> callback,
                int eventMask, bool immediateNotify) {
    CS_Status status = 0;
    m_handle = AddListener(
        [=](const RawEvent& event) {
          callback(static_cast<const VideoEvent&>(event));
        },
        eventMask, immediateNotify, &status);
  }

  VideoListener(const VideoListener&) = delete;
  VideoListener& operator=(const VideoListener&) = delete;

  VideoListener(VideoListener&& other) noexcept : VideoListener() {
    swap(*this, other);
  }

  VideoListener& operator=(VideoListener&& other) noexcept {
    swap(*this, other);
    return *this;
  }

  ~VideoListener() {
    CS_Status status = 0;
    if (m_handle != 0) {
      RemoveListener(m_handle, &status);
    }
  }

  friend void swap(VideoListener& first, VideoListener& second) noexcept {
    using std::swap;
    swap(first.m_handle, second.m_handle);
  }

 private:
  CS_Listener m_handle{0};
};

}  // namespace wpi::cs
