load("@allwpilib_pip_deps//:requirements.bzl", "requirement")
load("@bazel_lib//lib:write_source_files.bzl", "write_source_files")
load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_test")
load("@rules_java//java:defs.bzl", "java_binary")
load("@rules_python//python:defs.bzl", "py_binary")
load("//drivers:generate.bzl", "generate_drivers")
load("//drivers:robotpy_native_build_info.bzl", "define_native_wrapper")
load("//drivers:robotpy_pybind_build_info.bzl", "define_pybind_library", "drivers_extension")
load("//shared/bazel/rules:cc_rules.bzl", "third_party_cc_lib_helper", "wpilib_cc_library", "wpilib_cc_shared_library", "wpilib_cc_static_library")
load("//shared/bazel/rules:java_rules.bzl", "patch_module", "wpilib_java_junit5_test", "wpilib_java_library")
load("//shared/bazel/rules:packaging.bzl", "package_default_cc_project")
load("//shared/bazel/rules/robotpy:build_info_gen.bzl", "generate_robotpy_native_wrapper_build_info", "generate_robotpy_pybind_build_info")
load("//shared/bazel/rules/robotpy:pytest_util.bzl", "robotpy_py_test")

filegroup(
    name = "generated-native-include-files",
    srcs = glob(["src/generated/main/native/include/**/*"]),
    visibility = ["//drivers:__subpackages__"],
)

filegroup(
    name = "doxygen-files",
    srcs = glob(["src/main/native/include/**/*"]) + [":generated-native-include-files"],
    visibility = ["//visibility:public"],
)

py_binary(
    name = "generate_pwm_motor_controllers",
    srcs = ["generate_pwm_motor_controllers.py"],
    target_compatible_with = select({
        "@wpilib_toolchains//constraints/is_systemcore:systemcore": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    deps = [requirement("jinja2")],
)

filegroup(
    name = "templates",
    srcs = glob(["src/generate/**"]),
)

generate_drivers(
    name = "generate_drivers",
)

write_source_files(
    name = "write_drivers",
    diff_args = ["-u"],
    files = {
        "src/generated": ":generate_drivers",
    },
    suggested_update_target = "//:write_all",
    tags = ["pregeneration"],
    visibility = ["//visibility:public"],
)

third_party_cc_lib_helper(
    name = "generated_cc",
    include_root = "src/generated/main/native/include",
    src_root = "src/generated/main/native/cpp",
)

filegroup(
    name = "generated_java",
    srcs = glob(["src/generated/main/java/**/*.java"]),
)

wpilib_cc_library(
    name = "drivers",
    srcs = glob(["src/main/native/cpp/**"]),
    hdrs = glob(["src/main/native/include/**"]),
    includes = ["src/main/native/include"],
    strip_include_prefix = "src/main/native/include",
    third_party_libraries = [
        ":generated_cc",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//wpilibc",
    ],
)

wpilib_cc_shared_library(
    name = "shared/drivers",
    dynamic_deps = [
        "//datalog:shared/datalog",
        "//hal:shared/wpiHal",
        "//ntcore:shared/ntcore",
        "//telemetry:shared/telemetry",
        "//tunables:shared/tunables",
        "//wpilibc:shared/wpilibc",
        "//wpimath:shared/wpimath",
        "//wpinet:shared/wpinet",
        "//wpiutil:shared/wpiutil",
    ],
    visibility = ["//visibility:public"],
    deps = [":drivers"],
)

wpilib_cc_static_library(
    name = "static/drivers",
    static_deps = [
        "//datalog:static/datalog",
        "//hal:static/wpiHal",
        "//ntcore:static/ntcore",
        "//telemetry:static/telemetry",
        "//tunables:static/tunables",
        "//wpilibc:static/wpilibc",
        "//wpimath:static/wpimath",
        "//wpinet:static/wpinet",
        "//wpiutil:static/wpiutil",
    ],
    visibility = ["//visibility:public"],
    deps = [":drivers"],
)

wpilib_java_library(
    name = "drivers-java",
    srcs = glob(
        ["src/main/java/**/*.java"],
    ) + [":generated_java"],
    javacopts = patch_module(
        "wpilib.drivers",
        ["drivers/src/generated/main/java"],
    ),
    maven_artifact_name = "drivers-java",
    maven_group_id = "org.wpilib.drivers",
    visibility = ["//visibility:public"],
    deps = [
        "//hal:hal-java",
        "//ntcore:ntcore-java",
        "//telemetry:telemetry-java",
        "//tunables:tunables-java",
        "//wpilibj:wpilibj-java",
        "//wpimath:wpimath-java",
        "//wpiunits:wpiunits-java",
        "//wpiutil:wpiutil-java",
    ],
)

cc_test(
    name = "drivers-cpp-test",
    size = "small",
    srcs = glob(["src/test/native/**/*.cpp"]),
    tags = [
        "no-tsan",
        "no-ubsan",
    ],
    deps = [
        ":drivers",
        "//thirdparty/catch2",
    ],
)

wpilib_java_junit5_test(
    name = "drivers-java-test",
    srcs = glob(["src/test/java/**/*.java"]),
    deps = [
        ":drivers-java",
        "//hal:hal-java",
        "//ntcore:ntcore-java",
        "//telemetry:telemetry-java",
        "//tunables:tunables-java",
        "//wpilibj:wpilibj-java",
        "//wpimath:wpimath-java",
        "//wpiunits:wpiunits-java",
        "//wpiutil:wpiutil-java",
    ],
)

cc_binary(
    name = "DevMain-Cpp",
    srcs = ["src/dev/native/cpp/main.cpp"],
    deps = [":drivers"],
)

java_binary(
    name = "DevMain-Java",
    srcs = ["src/dev/java/org/wpilib/drivers/DevMain.java"],
    main_class = "org.wpilib.drivers.DevMain",
    deps = [":drivers-java"],
)

package_default_cc_project(
    name = "drivers",
    maven_artifact_name = "drivers-cpp",
    maven_group_id = "org.wpilib.drivers",
)

generate_robotpy_native_wrapper_build_info(
    name = "robotpy-native-wpilib-drivers-generator",
    generated_include_target = "//drivers:generated-native-include-files",
    pyproject_toml = "src/main/python/native-pyproject.toml",
)

define_native_wrapper(
    name = "robotpy-native-wpilib-drivers",
    pyproject_toml = "src/main/python/native-pyproject.toml",
)

PKG_CONFIG_DEPS = [
    "//datalog:native/datalog/robotpy-native-datalog.pc",
    "//datalog:robotpy-wpilog.generated_pkgcfg_files",
    "//drivers:native/wpilib_drivers/robotpy-native-wpilib-drivers.pc",
    "//hal:native/wpihal/robotpy-native-mrclib.pc",
    "//hal:native/wpihal/robotpy-native-wpihal.pc",
    "//hal:robotpy-hal.generated_pkgcfg_files",
    "//ntcore:native/ntcore/robotpy-native-ntcore.pc",
    "//ntcore:pyntcore.generated_pkgcfg_files",
    "//telemetry:native/telemetry/robotpy-native-telemetry.pc",
    "//telemetry:robotpy-telemetry.generated_pkgcfg_files",
    "//tunables:native/tunables/robotpy-native-tunables.pc",
    "//tunables:robotpy-tunables.generated_pkgcfg_files",
    "//wpilibc:native/wpilib/robotpy-native-wpilib.pc",
    "//wpilibc:robotpy-wpilib.generated_pkgcfg_files",
    "//wpimath:native/wpimath/robotpy-native-wpimath.pc",
    "//wpimath:robotpy-wpimath.generated_pkgcfg_files",
    "//wpinet:native/wpinet/robotpy-native-wpinet.pc",
    "//wpinet:robotpy-wpinet.generated_pkgcfg_files",
    "//wpiutil:native/wpiutil/robotpy-native-wpiutil.pc",
    "//wpiutil:robotpy-wpiutil.generated_pkgcfg_files",
]

generate_robotpy_pybind_build_info(
    name = "wpilib-drivers-generator",
    additional_srcs = [":robotpy-native-wpilib-drivers.copy_headers"],
    package_root_file = "src/main/python/wpilib_drivers/__init__.py",
    pkgcfgs = PKG_CONFIG_DEPS,
    yaml_files = glob(["src/main/python/semiwrap/**/*.yml"]),
)

drivers_extension(
    srcs = ["src/main/python/wpilib_drivers/src/main.cpp"],
)

define_pybind_library(
    name = "wpilib-drivers",
    pkgcfgs = PKG_CONFIG_DEPS,
)

robotpy_py_test(
    "python_tests",
    srcs = glob(["src/test/python/**/*.py"]),
    deps = [
        ":wpilib-drivers",
        requirement("pytest"),
    ],
)
