[tests]
base = [
  "ArcadeDrive",
  "ArcadeDriveXboxController",
  "ArmSimulation",
  "DifferentialDriveBot",
  "DifferentialDrivePoseEstimator",
  "DriveDistanceOffboard",
  "DutyCycleEncoder",
  "ElevatorExponentialProfile",
  "ElevatorExponentialSimulation",
  "ElevatorProfiledPID",
  "ElevatorSimulation",
  "ElevatorTrapezoidProfile",
  "Encoder",
  "ExpansionHubSample",
  "GettingStarted",
  "Gyro",
  "DSGamepadChooser",
  "HatchbotInlined",
  "HatchbotTraditional",
  "MecanumBot",
  "MecanumDrive",
  "MecanumDrivePoseEstimator",
  "Mechanism2d",
  "RapidReactCommandBot",
  "RomiReference",
  "SimpleDifferentialDriveSimulation",
  "StateSpaceArm",
  "StateSpaceElevator",
  "StateSpaceFlywheel",
  "StateSpaceFlywheelSysId",
  "SwerveBot",
  "SwerveDrivePoseEstimator",
  "SysId",
  "TankDrive",
  "TankDriveXboxController",
  "UnitTest",
  "XrpReference",
]

ignored = [
]
