load("@rules_cc//cc:cc_test.bzl", "cc_test")

filegroup(
    name = "sources",
    srcs = glob(["cpp/**/*.cpp"]),
    visibility = [
        "//wpilibcExamples/src/test/cpp/examples:__pkg__",
    ],
)

cc_test(
    name = "UnitTest",
    size = "small",
    srcs = [
        ":sources",
        "//wpilibcExamples/src/main/cpp/examples/UnitTest:cpp/Robot.cpp",
    ],
    defines = ["RUNNING_WPILIB_TESTS=1"],
    tags = [
        "exclusive-if-local",
        "no-asan",
        "no-tsan",
        "no-ubsan",
        "wpi-example",
    ],
    deps = [
        "//thirdparty/catch2",
        "//wpilibcExamples/src/main/cpp/examples/UnitTest:UnitTest_lib",
    ],
)
