load("@rules_cc//cc:cc_library.bzl", "cc_library")

filegroup(
    name = "sources",
    srcs = glob([
        "*.cpp",
        "*.hpp",
    ]),
    visibility = [
        "//wpilibcExamples/src/main/cpp/commands:__pkg__",
    ],
)

cc_library(
    name = "parallelracegroup",
    srcs = [":sources"],
    linkstatic = True,
    tags = [
        "wpi-example",
    ],
    deps = [
        "//commandsv2",
    ],
)
