load("@rules_cc//cc:cc_binary.bzl", "cc_binary")

filegroup(
    name = "sources",
    srcs = glob(["cpp/**/*.cpp"]),
    visibility = [
        "//wpilibcExamples/src/main/cpp/snippets:__pkg__",
    ],
)

cc_binary(
    name = "CANPDP",
    srcs = [":sources"],
    tags = [
        "wpi-example",
    ],
    deps = [
        "//wpilibc",
    ],
)
