load("@rules_jvm_external//:defs.bzl", "maven_export")
load("@rules_pkg//:pkg.bzl", "pkg_zip")

pkg_zip(
    name = "commands-zip",
    srcs = [
        "//:license_pkg_files",
        "//wpilibcExamples/src/main/cpp/commands",
    ],
    tags = ["manual"],
)

pkg_zip(
    name = "snippets-zip",
    srcs = [
        "//:license_pkg_files",
        "//wpilibcExamples/src/main/cpp/snippets",
    ],
    tags = ["manual"],
)

pkg_zip(
    name = "templates-zip",
    srcs = [
        "//:license_pkg_files",
        "//wpilibcExamples/src/main/cpp/templates",
    ],
    tags = ["manual"],
)

pkg_zip(
    name = "examples-zip",
    srcs = [
        "//:license_pkg_files",
        "//wpilibcExamples/src/main/cpp/examples",
        "//wpilibcExamples/src/test/cpp/examples",
    ],
    tags = ["manual"],
)

maven_export(
    name = "examples_publish",
    maven_coordinates = "org.wpilib.wpilibc:examples:$(WPILIB_VERSION)",
    target = ":examples-zip",
    visibility = ["//visibility:public"],
)

maven_export(
    name = "commands_publish",
    maven_coordinates = "org.wpilib.wpilibc:commands:$(WPILIB_VERSION)",
    target = ":commands-zip",
    visibility = ["//visibility:public"],
)

maven_export(
    name = "templates_publish",
    maven_coordinates = "org.wpilib.wpilibc:templates:$(WPILIB_VERSION)",
    target = ":templates-zip",
    visibility = ["//visibility:public"],
)
