load("@bzlmodrio-opencv//libraries/cpp/opencv:libraries.bzl", "opencv_shared_libraries")

EXAMPLE_FOLDERS = {
    "ArcadeDriveGamepad": (["//commandsv2"], ["//commandsv2:shared/commandsv2"]),
    "ArmSimulation": (["//commandsv2"], ["//commandsv2:shared/commandsv2"]),
    "DSGamepadChooser": (["//commandsv2"], ["//commandsv2:shared/commandsv2"]),
    "DifferentialDriveBot": (["//commandsv2"], ["//commandsv2:shared/commandsv2"]),
    "DifferentialDrivePoseEstimator": (["//commandsv2"], ["//commandsv2:shared/commandsv2"]),
    "DriveDistanceOffboard": (["//commandsv2"], ["//commandsv2:shared/commandsv2"]),
    "DriverStationDisplayAnsi": (["//commandsv2"], ["//commandsv2:shared/commandsv2"]),
    "DriverStationDisplayLines": (["//commandsv2"], ["//commandsv2:shared/commandsv2"]),
    "DutyCycleEncoder": (["//commandsv2"], ["//commandsv2:shared/commandsv2"]),
    "ElevatorExponentialProfile": (["//commandsv2"], ["//commandsv2:shared/commandsv2"]),
    "ElevatorExponentialSimulation": (["//commandsv2"], ["//commandsv2:shared/commandsv2"]),
    "ElevatorProfiledPID": (["//commandsv2"], ["//commandsv2:shared/commandsv2"]),
    "ElevatorSimulation": (["//commandsv2"], ["//commandsv2:shared/commandsv2"]),
    "ElevatorTrapezoidProfile": (["//commandsv2"], ["//commandsv2:shared/commandsv2"]),
    "Encoder": (["//commandsv2"], ["//commandsv2:shared/commandsv2"]),
    "GettingStarted": (["//commandsv2"], ["//commandsv2:shared/commandsv2"]),
    "Gyro": (["//commandsv2"], ["//commandsv2:shared/commandsv2"]),
    "HAL": (["//commandsv2"], ["//commandsv2:shared/commandsv2"]),
    "HatchbotInlined": (["//commandsv2"], ["//commandsv2:shared/commandsv2"]),
    "HatchbotTraditional": (["//commandsv2"], ["//commandsv2:shared/commandsv2"]),
    "MecanumBot": (["//commandsv2"], ["//commandsv2:shared/commandsv2"]),
    "MecanumDrive": (["//commandsv2"], ["//commandsv2:shared/commandsv2"]),
    "MecanumDrivePoseEstimator": (["//commandsv2"], ["//commandsv2:shared/commandsv2"]),
    "Mechanism2d": (["//commandsv2"], ["//commandsv2:shared/commandsv2"]),
    "RapidReactCommandBot": (["//commandsv2"], ["//commandsv2:shared/commandsv2"]),
    "RomiReference": (["//commandsv2", "//romiVendordep"], ["//commandsv2:shared/commandsv2", "//romiVendordep:shared/romiVendordep"]),
    "SimpleDifferentialDriveSimulation": (["//commandsv2"], ["//commandsv2:shared/commandsv2"]),
    "StateSpaceArm": (["//commandsv2"], ["//commandsv2:shared/commandsv2"]),
    "StateSpaceElevator": (["//commandsv2"], ["//commandsv2:shared/commandsv2"]),
    "StateSpaceFlywheel": (["//commandsv2"], ["//commandsv2:shared/commandsv2"]),
    "StateSpaceFlywheelSysId": (["//commandsv2"], ["//commandsv2:shared/commandsv2"]),
    "SwerveBot": (["//commandsv2"], ["//commandsv2:shared/commandsv2"]),
    "SwerveDrivePoseEstimator": (["//commandsv2"], ["//commandsv2:shared/commandsv2"]),
    "SysIdRoutine": (["//commandsv2"], ["//commandsv2:shared/commandsv2"]),
    "TankDriveGamepad": (["//commandsv2"], ["//commandsv2:shared/commandsv2"]),
    "UnitTest": (["//commandsv2"], ["//commandsv2:shared/commandsv2"]),
    "XRPReference": (["//commandsv2", "//xrpVendordep"], ["//commandsv2:shared/commandsv2", "//xrpVendordep:shared/xrpVendordep"]),
    "Xrptimed": (["//commandsv2", "//xrpVendordep"], ["//commandsv2:shared/commandsv2", "//xrpVendordep:shared/xrpVendordep"]),
}

COMMANDS_V2_FOLDERS = {
    "command2": (["//commandsv2"], ["//commandsv2:shared/commandsv2"]),
    "emptyclass": ([], []),
    "instantcommand": (["//commandsv2"], ["//commandsv2:shared/commandsv2"]),
    "parallelcommandgroup": (["//commandsv2"], ["//commandsv2:shared/commandsv2"]),
    "paralleldeadlinegroup": (["//commandsv2"], ["//commandsv2:shared/commandsv2"]),
    "parallelracegroup": (["//commandsv2"], ["//commandsv2:shared/commandsv2"]),
    "sequentialcommandgroup": (["//commandsv2"], ["//commandsv2:shared/commandsv2"]),
    "subsystem2": (["//commandsv2"], ["//commandsv2:shared/commandsv2"]),
}

SNIPPET_FOLDERS = {
    "ADXLAccelerometers": ([], []),
    "AccelerometerCollision": ([], []),
    "AccelerometerFilter": ([], []),
    "AddressableLED": ([], []),
    "AnalogAccelerometer": ([], []),
    "AnalogEncoder": ([], []),
    "AnalogInput": ([], []),
    "AnalogPotentiometer": ([], []),
    "AprilTagsVision": (["//cameraserver"], opencv_shared_libraries + ["//cameraserver:shared/cameraserver", "//cscore:shared/cscore"]),
    "CANPDP": ([], []),
    "DifferentialDrive": ([], []),
    "DigitalCommunication": ([], []),
    "DigitalInput": ([], []),
    "DutyCycleEncoder": ([], []),
    "DutyCycleInput": ([], []),
    "Encoder": ([], []),
    "EncoderDrive": ([], []),
    "EncoderHoming": ([], []),
    "EventLoop": ([], []),
    "FlywheelBangBangController": ([], []),
    "HttpCamera": (["//cameraserver"], opencv_shared_libraries + ["//cameraserver:shared/cameraserver", "//cscore:shared/cscore"]),
    "I2CCommunication": ([], []),
    "IntermediateVision": (["//cameraserver"], opencv_shared_libraries + ["//cameraserver:shared/cameraserver", "//cscore:shared/cscore"]),
    "LimitSwitch": ([], []),
    "MecanumDrive": ([], []),
    "MotorControl": ([], []),
    "OnboardIMU": ([], []),
    "ProfiledPIDFeedforward": ([], []),
    "QuickVision": (["//cameraserver"], opencv_shared_libraries + ["//cameraserver:shared/cameraserver", "//cscore:shared/cscore"]),
    "SelectCommand": (["//commandsv2"], ["//commandsv2:shared/commandsv2"]),
    "Solenoid": ([], []),
}

TEMPLATE_FOLDERS = {
    "commandv2": (["//commandsv2"], ["//commandsv2:shared/commandsv2"]),
    "commandv2skeleton": (["//commandsv2"], ["//commandsv2:shared/commandsv2"]),
    "opmode": (["//commandsv2"], ["//commandsv2:shared/commandsv2"]),
    "robotbaseskeleton": (["//commandsv2"], ["//commandsv2:shared/commandsv2"]),
    "timed": (["//commandsv2"], ["//commandsv2:shared/commandsv2"]),
    "timedskeleton": (["//commandsv2"], ["//commandsv2:shared/commandsv2"]),
    "timeslice": (["//commandsv2"], ["//commandsv2:shared/commandsv2"]),
    "timesliceskeleton": (["//commandsv2"], ["//commandsv2:shared/commandsv2"]),
}

EXAMPLE_TESTS_FOLDERS = {
    "ArmSimulation": ([], []),
    "ElevatorSimulation": ([], []),
    "UnitTest": ([], []),
}

SNIPPET_TESTS_FOLDERS = {
    "DigitalCommunication": ([], []),
    "I2CCommunication": ([], []),
}
