EXAMPLE_FOLDERS = [
    "ArcadeDriveGamepad",
    "ArmSimulation",
    "DifferentialDriveBot",
    "DifferentialDrivePoseEstimator",
    "DriveDistanceOffboard",
    "DutyCycleEncoder",
    "ElevatorExponentialProfile",
    "ElevatorExponentialSimulation",
    "ElevatorProfiledPID",
    "ElevatorSimulation",
    "ElevatorTrapezoidProfile",
    "Encoder",
    "GettingStarted",
    "Gyro",
    "HAL",
    "HatchbotInlined",
    "HatchbotTraditional",
    "MecanumBot",
    "MecanumDrive",
    "MecanumDrivePoseEstimator",
    "Mechanism2d",
    "RapidReactCommandBot",
    "RomiReference",
    "SimpleDifferentialDriveSimulation",
    "StateSpaceArm",
    "StateSpaceElevator",
    "StateSpaceFlywheel",
    "StateSpaceFlywheelSysId",
    "SwerveBot",
    "SwerveDrivePoseEstimator",
    "SysIdRoutine",
    "TankDriveGamepad",
    "UnitTest",
    "XRPReference",
    "Xrptimed",
]

COMMANDS_V2_FOLDERS = [
    "command2",
    "emptyclass",
    "instantcommand",
    "parallelcommandgroup",
    "paralleldeadlinegroup",
    "parallelracegroup",
    "sequentialcommandgroup",
    "subsystem2",
]

SNIPPET_FOLDERS = [
    "ADXLAccelerometers",
    "AccelerometerCollision",
    "AccelerometerFilter",
    "AddressableLED",
    "AnalogAccelerometer",
    "AnalogEncoder",
    "AnalogInput",
    "AnalogPotentiometer",
    "AprilTagsVision",
    "CANPDP",
    "DigitalCommunication",
    "DigitalInput",
    "DutyCycleEncoder",
    "DutyCycleInput",
    "Encoder",
    "EncoderDrive",
    "EncoderHoming",
    "EventLoop",
    "FlywheelBangBangController",
    "HttpCamera",
    "I2CCommunication",
    "IntermediateVision",
    "LimitSwitch",
    "MotorControl",
    "OnboardIMU",
    "ProfiledPIDFeedforward",
    "QuickVision",
    "SelectCommand",
    "Solenoid",
]

TEMPLATE_FOLDERS = [
    "commandv2",
    "commandv2skeleton",
    "opmode",
    "robotbaseskeleton",
    "timed",
    "timedskeleton",
    "timeslice",
    "timesliceskeleton",
]

EXAMPLE_TESTS_FOLDERS = [
    "ArmSimulation",
    "ElevatorSimulation",
    "UnitTest",
]

SNIPPET_TESTS_FOLDERS = [
    "DigitalCommunication",
    "I2CCommunication",
]
