set(GCC_COMPILER_VERSION "" CACHE STRING "GCC Compiler version")
set(GNU_MACHINE "arm-frc2024-linux-gnueabi" CACHE STRING "GNU compiler triple")
set(SOFTFP yes)
set(ARM_LINUX_SYSROOT /usr/local/arm-nilrt-linux-gnueabi/sysroot)
include("${CMAKE_CURRENT_LIST_DIR}/arm.toolchain.cmake")
