include(CMakeFindDependencyMacro)
 @FILENAME_DEP_REPLACE@
 @WPIUTIL_DEP_REPLACE@
 @NTCORE_DEP_REPLACE@
 @CSCORE_DEP_REPLACE@
 @CAMERASERVER_DEP_REPLACE@
 @HAL_DEP_REPLACE@
 @WPILIBC_DEP_REPLACE@
 @WPIMATH_DEP_REPLACE@

 include(${SELF_DIR}/wpilibNewCommands.cmake)
