/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#define SWIGJAVA


#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  jenv->ExceptionClear();
  excep = jenv->FindClass(except_ptr->java_exception);
  if (excep)
    jenv->ThrowNew(excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include "ctre/CanTalonSRX.h"


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jlong JNICALL Java_edu_wpi_first_wpilibj_hal_CanTalonJNI_new_1CtreCanNode(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  UINT8 arg1 ;
  UINT8 *argp1 ;
  CtreCanNode *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  argp1 = *(UINT8 **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null UINT8");
    return 0;
  }
  arg1 = *argp1; 
  result = (CtreCanNode *)new CtreCanNode(arg1);
  *(CtreCanNode **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_edu_wpi_first_wpilibj_hal_CanTalonJNI_delete_1CtreCanNode(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  CtreCanNode *arg1 = (CtreCanNode *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CtreCanNode **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jlong JNICALL Java_edu_wpi_first_wpilibj_hal_CanTalonJNI_CtreCanNode_1GetDeviceNumber(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  CtreCanNode *arg1 = (CtreCanNode *) 0 ;
  UINT8 result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CtreCanNode **)&jarg1; 
  result = (arg1)->GetDeviceNumber();
  *(UINT8 **)&jresult = new UINT8((const UINT8 &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_wpi_first_wpilibj_hal_CanTalonJNI_new_1CanTalonSRX_1_1SWIG_10(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jlong jresult = 0 ;
  int arg1 ;
  CanTalonSRX *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (CanTalonSRX *)new CanTalonSRX(arg1);
  *(CanTalonSRX **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_wpi_first_wpilibj_hal_CanTalonJNI_new_1CanTalonSRX_1_1SWIG_11(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  CanTalonSRX *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (CanTalonSRX *)new CanTalonSRX();
  *(CanTalonSRX **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_edu_wpi_first_wpilibj_hal_CanTalonJNI_delete_1CanTalonSRX(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  CanTalonSRX *arg1 = (CanTalonSRX *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CanTalonSRX **)&jarg1; 
  delete arg1;
}


SWIGEXPORT void JNICALL Java_edu_wpi_first_wpilibj_hal_CanTalonJNI_CanTalonSRX_1Set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  CanTalonSRX *arg1 = (CanTalonSRX *) 0 ;
  double arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CanTalonSRX **)&jarg1; 
  arg2 = (double)jarg2; 
  (arg1)->Set(arg2);
}


SWIGEXPORT jlong JNICALL Java_edu_wpi_first_wpilibj_hal_CanTalonJNI_CanTalonSRX_1GetFault_1OverTemp(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jlong jresult = 0 ;
  CanTalonSRX *arg1 = (CanTalonSRX *) 0 ;
  int *arg2 = 0 ;
  CTR_Code result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CanTalonSRX **)&jarg1; 
  arg2 = *(int **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "int & reference is null");
    return 0;
  } 
  result = (arg1)->GetFault_OverTemp(*arg2);
  *(CTR_Code **)&jresult = new CTR_Code((const CTR_Code &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_wpi_first_wpilibj_hal_CanTalonJNI_CanTalonSRX_1GetFault_1UnderVoltage(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jlong jresult = 0 ;
  CanTalonSRX *arg1 = (CanTalonSRX *) 0 ;
  int *arg2 = 0 ;
  CTR_Code result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CanTalonSRX **)&jarg1; 
  arg2 = *(int **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "int & reference is null");
    return 0;
  } 
  result = (arg1)->GetFault_UnderVoltage(*arg2);
  *(CTR_Code **)&jresult = new CTR_Code((const CTR_Code &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_wpi_first_wpilibj_hal_CanTalonJNI_CanTalonSRX_1GetFault_1ForLim(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jlong jresult = 0 ;
  CanTalonSRX *arg1 = (CanTalonSRX *) 0 ;
  int *arg2 = 0 ;
  CTR_Code result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CanTalonSRX **)&jarg1; 
  arg2 = *(int **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "int & reference is null");
    return 0;
  } 
  result = (arg1)->GetFault_ForLim(*arg2);
  *(CTR_Code **)&jresult = new CTR_Code((const CTR_Code &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_wpi_first_wpilibj_hal_CanTalonJNI_CanTalonSRX_1GetFault_1RevLim(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jlong jresult = 0 ;
  CanTalonSRX *arg1 = (CanTalonSRX *) 0 ;
  int *arg2 = 0 ;
  CTR_Code result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CanTalonSRX **)&jarg1; 
  arg2 = *(int **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "int & reference is null");
    return 0;
  } 
  result = (arg1)->GetFault_RevLim(*arg2);
  *(CTR_Code **)&jresult = new CTR_Code((const CTR_Code &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_wpi_first_wpilibj_hal_CanTalonJNI_CanTalonSRX_1GetFault_1HardwareFailure(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jlong jresult = 0 ;
  CanTalonSRX *arg1 = (CanTalonSRX *) 0 ;
  int *arg2 = 0 ;
  CTR_Code result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CanTalonSRX **)&jarg1; 
  arg2 = *(int **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "int & reference is null");
    return 0;
  } 
  result = (arg1)->GetFault_HardwareFailure(*arg2);
  *(CTR_Code **)&jresult = new CTR_Code((const CTR_Code &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_wpi_first_wpilibj_hal_CanTalonJNI_CanTalonSRX_1GetFault_1ForSoftLim(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jlong jresult = 0 ;
  CanTalonSRX *arg1 = (CanTalonSRX *) 0 ;
  int *arg2 = 0 ;
  CTR_Code result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CanTalonSRX **)&jarg1; 
  arg2 = *(int **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "int & reference is null");
    return 0;
  } 
  result = (arg1)->GetFault_ForSoftLim(*arg2);
  *(CTR_Code **)&jresult = new CTR_Code((const CTR_Code &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_wpi_first_wpilibj_hal_CanTalonJNI_CanTalonSRX_1GetFault_1RevSoftLim(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jlong jresult = 0 ;
  CanTalonSRX *arg1 = (CanTalonSRX *) 0 ;
  int *arg2 = 0 ;
  CTR_Code result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CanTalonSRX **)&jarg1; 
  arg2 = *(int **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "int & reference is null");
    return 0;
  } 
  result = (arg1)->GetFault_RevSoftLim(*arg2);
  *(CTR_Code **)&jresult = new CTR_Code((const CTR_Code &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_wpi_first_wpilibj_hal_CanTalonJNI_CanTalonSRX_1GetStckyFault_1OverTemp(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jlong jresult = 0 ;
  CanTalonSRX *arg1 = (CanTalonSRX *) 0 ;
  int *arg2 = 0 ;
  CTR_Code result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CanTalonSRX **)&jarg1; 
  arg2 = *(int **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "int & reference is null");
    return 0;
  } 
  result = (arg1)->GetStckyFault_OverTemp(*arg2);
  *(CTR_Code **)&jresult = new CTR_Code((const CTR_Code &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_wpi_first_wpilibj_hal_CanTalonJNI_CanTalonSRX_1GetStckyFault_1UnderVoltage(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jlong jresult = 0 ;
  CanTalonSRX *arg1 = (CanTalonSRX *) 0 ;
  int *arg2 = 0 ;
  CTR_Code result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CanTalonSRX **)&jarg1; 
  arg2 = *(int **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "int & reference is null");
    return 0;
  } 
  result = (arg1)->GetStckyFault_UnderVoltage(*arg2);
  *(CTR_Code **)&jresult = new CTR_Code((const CTR_Code &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_wpi_first_wpilibj_hal_CanTalonJNI_CanTalonSRX_1GetStckyFault_1ForLim(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jlong jresult = 0 ;
  CanTalonSRX *arg1 = (CanTalonSRX *) 0 ;
  int *arg2 = 0 ;
  CTR_Code result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CanTalonSRX **)&jarg1; 
  arg2 = *(int **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "int & reference is null");
    return 0;
  } 
  result = (arg1)->GetStckyFault_ForLim(*arg2);
  *(CTR_Code **)&jresult = new CTR_Code((const CTR_Code &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_wpi_first_wpilibj_hal_CanTalonJNI_CanTalonSRX_1GetStckyFault_1RevLim(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jlong jresult = 0 ;
  CanTalonSRX *arg1 = (CanTalonSRX *) 0 ;
  int *arg2 = 0 ;
  CTR_Code result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CanTalonSRX **)&jarg1; 
  arg2 = *(int **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "int & reference is null");
    return 0;
  } 
  result = (arg1)->GetStckyFault_RevLim(*arg2);
  *(CTR_Code **)&jresult = new CTR_Code((const CTR_Code &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_wpi_first_wpilibj_hal_CanTalonJNI_CanTalonSRX_1GetStckyFault_1ForSoftLim(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jlong jresult = 0 ;
  CanTalonSRX *arg1 = (CanTalonSRX *) 0 ;
  int *arg2 = 0 ;
  CTR_Code result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CanTalonSRX **)&jarg1; 
  arg2 = *(int **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "int & reference is null");
    return 0;
  } 
  result = (arg1)->GetStckyFault_ForSoftLim(*arg2);
  *(CTR_Code **)&jresult = new CTR_Code((const CTR_Code &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_wpi_first_wpilibj_hal_CanTalonJNI_CanTalonSRX_1GetStckyFault_1RevSoftLim(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jlong jresult = 0 ;
  CanTalonSRX *arg1 = (CanTalonSRX *) 0 ;
  int *arg2 = 0 ;
  CTR_Code result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CanTalonSRX **)&jarg1; 
  arg2 = *(int **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "int & reference is null");
    return 0;
  } 
  result = (arg1)->GetStckyFault_RevSoftLim(*arg2);
  *(CTR_Code **)&jresult = new CTR_Code((const CTR_Code &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_wpi_first_wpilibj_hal_CanTalonJNI_CanTalonSRX_1GetAppliedThrottle11(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jlong jresult = 0 ;
  CanTalonSRX *arg1 = (CanTalonSRX *) 0 ;
  int *arg2 = 0 ;
  CTR_Code result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CanTalonSRX **)&jarg1; 
  arg2 = *(int **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "int & reference is null");
    return 0;
  } 
  result = (arg1)->GetAppliedThrottle11(*arg2);
  *(CTR_Code **)&jresult = new CTR_Code((const CTR_Code &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_wpi_first_wpilibj_hal_CanTalonJNI_CanTalonSRX_1GetCloseLoopErr(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jlong jresult = 0 ;
  CanTalonSRX *arg1 = (CanTalonSRX *) 0 ;
  int *arg2 = 0 ;
  CTR_Code result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CanTalonSRX **)&jarg1; 
  arg2 = *(int **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "int & reference is null");
    return 0;
  } 
  result = (arg1)->GetCloseLoopErr(*arg2);
  *(CTR_Code **)&jresult = new CTR_Code((const CTR_Code &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_wpi_first_wpilibj_hal_CanTalonJNI_CanTalonSRX_1GetSelectlFeedbackDevice(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jlong jresult = 0 ;
  CanTalonSRX *arg1 = (CanTalonSRX *) 0 ;
  int *arg2 = 0 ;
  CTR_Code result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CanTalonSRX **)&jarg1; 
  arg2 = *(int **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "int & reference is null");
    return 0;
  } 
  result = (arg1)->GetSelectlFeedbackDevice(*arg2);
  *(CTR_Code **)&jresult = new CTR_Code((const CTR_Code &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_wpi_first_wpilibj_hal_CanTalonJNI_CanTalonSRX_1GetModeSelect(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jlong jresult = 0 ;
  CanTalonSRX *arg1 = (CanTalonSRX *) 0 ;
  int *arg2 = 0 ;
  CTR_Code result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CanTalonSRX **)&jarg1; 
  arg2 = *(int **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "int & reference is null");
    return 0;
  } 
  result = (arg1)->GetModeSelect(*arg2);
  *(CTR_Code **)&jresult = new CTR_Code((const CTR_Code &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_wpi_first_wpilibj_hal_CanTalonJNI_CanTalonSRX_1GetLimitSwitchEn(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jlong jresult = 0 ;
  CanTalonSRX *arg1 = (CanTalonSRX *) 0 ;
  int *arg2 = 0 ;
  CTR_Code result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CanTalonSRX **)&jarg1; 
  arg2 = *(int **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "int & reference is null");
    return 0;
  } 
  result = (arg1)->GetLimitSwitchEn(*arg2);
  *(CTR_Code **)&jresult = new CTR_Code((const CTR_Code &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_wpi_first_wpilibj_hal_CanTalonJNI_CanTalonSRX_1GetLimitSwitchClosedFor(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jlong jresult = 0 ;
  CanTalonSRX *arg1 = (CanTalonSRX *) 0 ;
  int *arg2 = 0 ;
  CTR_Code result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CanTalonSRX **)&jarg1; 
  arg2 = *(int **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "int & reference is null");
    return 0;
  } 
  result = (arg1)->GetLimitSwitchClosedFor(*arg2);
  *(CTR_Code **)&jresult = new CTR_Code((const CTR_Code &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_wpi_first_wpilibj_hal_CanTalonJNI_CanTalonSRX_1GetLimitSwitchClosedRev(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jlong jresult = 0 ;
  CanTalonSRX *arg1 = (CanTalonSRX *) 0 ;
  int *arg2 = 0 ;
  CTR_Code result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CanTalonSRX **)&jarg1; 
  arg2 = *(int **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "int & reference is null");
    return 0;
  } 
  result = (arg1)->GetLimitSwitchClosedRev(*arg2);
  *(CTR_Code **)&jresult = new CTR_Code((const CTR_Code &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_wpi_first_wpilibj_hal_CanTalonJNI_CanTalonSRX_1GetCloseLoopCellSelect(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jlong jresult = 0 ;
  CanTalonSRX *arg1 = (CanTalonSRX *) 0 ;
  int *arg2 = 0 ;
  CTR_Code result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CanTalonSRX **)&jarg1; 
  arg2 = *(int **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "int & reference is null");
    return 0;
  } 
  result = (arg1)->GetCloseLoopCellSelect(*arg2);
  *(CTR_Code **)&jresult = new CTR_Code((const CTR_Code &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_wpi_first_wpilibj_hal_CanTalonJNI_CanTalonSRX_1GetSensorPosition(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jlong jresult = 0 ;
  CanTalonSRX *arg1 = (CanTalonSRX *) 0 ;
  int *arg2 = 0 ;
  CTR_Code result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CanTalonSRX **)&jarg1; 
  arg2 = *(int **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "int & reference is null");
    return 0;
  } 
  result = (arg1)->GetSensorPosition(*arg2);
  *(CTR_Code **)&jresult = new CTR_Code((const CTR_Code &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_wpi_first_wpilibj_hal_CanTalonJNI_CanTalonSRX_1GetSensorVelocity(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jlong jresult = 0 ;
  CanTalonSRX *arg1 = (CanTalonSRX *) 0 ;
  int *arg2 = 0 ;
  CTR_Code result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CanTalonSRX **)&jarg1; 
  arg2 = *(int **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "int & reference is null");
    return 0;
  } 
  result = (arg1)->GetSensorVelocity(*arg2);
  *(CTR_Code **)&jresult = new CTR_Code((const CTR_Code &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_wpi_first_wpilibj_hal_CanTalonJNI_CanTalonSRX_1GetCurrent(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jlong jresult = 0 ;
  CanTalonSRX *arg1 = (CanTalonSRX *) 0 ;
  double *arg2 = 0 ;
  CTR_Code result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CanTalonSRX **)&jarg1; 
  arg2 = *(double **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "double & reference is null");
    return 0;
  } 
  result = (arg1)->GetCurrent(*arg2);
  *(CTR_Code **)&jresult = new CTR_Code((const CTR_Code &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_wpi_first_wpilibj_hal_CanTalonJNI_CanTalonSRX_1GetBrakeIsEnabled(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jlong jresult = 0 ;
  CanTalonSRX *arg1 = (CanTalonSRX *) 0 ;
  int *arg2 = 0 ;
  CTR_Code result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CanTalonSRX **)&jarg1; 
  arg2 = *(int **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "int & reference is null");
    return 0;
  } 
  result = (arg1)->GetBrakeIsEnabled(*arg2);
  *(CTR_Code **)&jresult = new CTR_Code((const CTR_Code &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_wpi_first_wpilibj_hal_CanTalonJNI_CanTalonSRX_1GetEncPosition(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jlong jresult = 0 ;
  CanTalonSRX *arg1 = (CanTalonSRX *) 0 ;
  int *arg2 = 0 ;
  CTR_Code result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CanTalonSRX **)&jarg1; 
  arg2 = *(int **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "int & reference is null");
    return 0;
  } 
  result = (arg1)->GetEncPosition(*arg2);
  *(CTR_Code **)&jresult = new CTR_Code((const CTR_Code &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_wpi_first_wpilibj_hal_CanTalonJNI_CanTalonSRX_1GetEncVel(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jlong jresult = 0 ;
  CanTalonSRX *arg1 = (CanTalonSRX *) 0 ;
  int *arg2 = 0 ;
  CTR_Code result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CanTalonSRX **)&jarg1; 
  arg2 = *(int **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "int & reference is null");
    return 0;
  } 
  result = (arg1)->GetEncVel(*arg2);
  *(CTR_Code **)&jresult = new CTR_Code((const CTR_Code &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_wpi_first_wpilibj_hal_CanTalonJNI_CanTalonSRX_1GetEncIndexRiseEvents(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jlong jresult = 0 ;
  CanTalonSRX *arg1 = (CanTalonSRX *) 0 ;
  int *arg2 = 0 ;
  CTR_Code result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CanTalonSRX **)&jarg1; 
  arg2 = *(int **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "int & reference is null");
    return 0;
  } 
  result = (arg1)->GetEncIndexRiseEvents(*arg2);
  *(CTR_Code **)&jresult = new CTR_Code((const CTR_Code &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_wpi_first_wpilibj_hal_CanTalonJNI_CanTalonSRX_1GetQuadApin(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jlong jresult = 0 ;
  CanTalonSRX *arg1 = (CanTalonSRX *) 0 ;
  int *arg2 = 0 ;
  CTR_Code result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CanTalonSRX **)&jarg1; 
  arg2 = *(int **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "int & reference is null");
    return 0;
  } 
  result = (arg1)->GetQuadApin(*arg2);
  *(CTR_Code **)&jresult = new CTR_Code((const CTR_Code &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_wpi_first_wpilibj_hal_CanTalonJNI_CanTalonSRX_1GetQuadBpin(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jlong jresult = 0 ;
  CanTalonSRX *arg1 = (CanTalonSRX *) 0 ;
  int *arg2 = 0 ;
  CTR_Code result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CanTalonSRX **)&jarg1; 
  arg2 = *(int **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "int & reference is null");
    return 0;
  } 
  result = (arg1)->GetQuadBpin(*arg2);
  *(CTR_Code **)&jresult = new CTR_Code((const CTR_Code &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_wpi_first_wpilibj_hal_CanTalonJNI_CanTalonSRX_1GetQuadIdxpin(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jlong jresult = 0 ;
  CanTalonSRX *arg1 = (CanTalonSRX *) 0 ;
  int *arg2 = 0 ;
  CTR_Code result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CanTalonSRX **)&jarg1; 
  arg2 = *(int **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "int & reference is null");
    return 0;
  } 
  result = (arg1)->GetQuadIdxpin(*arg2);
  *(CTR_Code **)&jresult = new CTR_Code((const CTR_Code &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_wpi_first_wpilibj_hal_CanTalonJNI_CanTalonSRX_1GetAnalogInWithOv(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jlong jresult = 0 ;
  CanTalonSRX *arg1 = (CanTalonSRX *) 0 ;
  int *arg2 = 0 ;
  CTR_Code result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CanTalonSRX **)&jarg1; 
  arg2 = *(int **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "int & reference is null");
    return 0;
  } 
  result = (arg1)->GetAnalogInWithOv(*arg2);
  *(CTR_Code **)&jresult = new CTR_Code((const CTR_Code &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_wpi_first_wpilibj_hal_CanTalonJNI_CanTalonSRX_1GetAnalogInVel(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jlong jresult = 0 ;
  CanTalonSRX *arg1 = (CanTalonSRX *) 0 ;
  int *arg2 = 0 ;
  CTR_Code result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CanTalonSRX **)&jarg1; 
  arg2 = *(int **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "int & reference is null");
    return 0;
  } 
  result = (arg1)->GetAnalogInVel(*arg2);
  *(CTR_Code **)&jresult = new CTR_Code((const CTR_Code &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_wpi_first_wpilibj_hal_CanTalonJNI_CanTalonSRX_1GetTemp(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jlong jresult = 0 ;
  CanTalonSRX *arg1 = (CanTalonSRX *) 0 ;
  double *arg2 = 0 ;
  CTR_Code result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CanTalonSRX **)&jarg1; 
  arg2 = *(double **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "double & reference is null");
    return 0;
  } 
  result = (arg1)->GetTemp(*arg2);
  *(CTR_Code **)&jresult = new CTR_Code((const CTR_Code &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_wpi_first_wpilibj_hal_CanTalonJNI_CanTalonSRX_1GetBatteryV(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jlong jresult = 0 ;
  CanTalonSRX *arg1 = (CanTalonSRX *) 0 ;
  double *arg2 = 0 ;
  CTR_Code result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CanTalonSRX **)&jarg1; 
  arg2 = *(double **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "double & reference is null");
    return 0;
  } 
  result = (arg1)->GetBatteryV(*arg2);
  *(CTR_Code **)&jresult = new CTR_Code((const CTR_Code &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_wpi_first_wpilibj_hal_CanTalonJNI_CanTalonSRX_1GetResetCount(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jlong jresult = 0 ;
  CanTalonSRX *arg1 = (CanTalonSRX *) 0 ;
  int *arg2 = 0 ;
  CTR_Code result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CanTalonSRX **)&jarg1; 
  arg2 = *(int **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "int & reference is null");
    return 0;
  } 
  result = (arg1)->GetResetCount(*arg2);
  *(CTR_Code **)&jresult = new CTR_Code((const CTR_Code &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_wpi_first_wpilibj_hal_CanTalonJNI_CanTalonSRX_1GetResetFlags(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jlong jresult = 0 ;
  CanTalonSRX *arg1 = (CanTalonSRX *) 0 ;
  int *arg2 = 0 ;
  CTR_Code result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CanTalonSRX **)&jarg1; 
  arg2 = *(int **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "int & reference is null");
    return 0;
  } 
  result = (arg1)->GetResetFlags(*arg2);
  *(CTR_Code **)&jresult = new CTR_Code((const CTR_Code &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_wpi_first_wpilibj_hal_CanTalonJNI_CanTalonSRX_1GetFirmVers(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jlong jresult = 0 ;
  CanTalonSRX *arg1 = (CanTalonSRX *) 0 ;
  int *arg2 = 0 ;
  CTR_Code result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CanTalonSRX **)&jarg1; 
  arg2 = *(int **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "int & reference is null");
    return 0;
  } 
  result = (arg1)->GetFirmVers(*arg2);
  *(CTR_Code **)&jresult = new CTR_Code((const CTR_Code &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_wpi_first_wpilibj_hal_CanTalonJNI_CanTalonSRX_1SetDemand24(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jlong jresult = 0 ;
  CanTalonSRX *arg1 = (CanTalonSRX *) 0 ;
  int arg2 ;
  CTR_Code result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CanTalonSRX **)&jarg1; 
  arg2 = (int)jarg2; 
  result = (arg1)->SetDemand24(arg2);
  *(CTR_Code **)&jresult = new CTR_Code((const CTR_Code &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_wpi_first_wpilibj_hal_CanTalonJNI_CanTalonSRX_1SetLimitSwitchEn(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jlong jresult = 0 ;
  CanTalonSRX *arg1 = (CanTalonSRX *) 0 ;
  int arg2 ;
  CTR_Code result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CanTalonSRX **)&jarg1; 
  arg2 = (int)jarg2; 
  result = (arg1)->SetLimitSwitchEn(arg2);
  *(CTR_Code **)&jresult = new CTR_Code((const CTR_Code &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_wpi_first_wpilibj_hal_CanTalonJNI_CanTalonSRX_1SetSelectlFeedbackDevice(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jlong jresult = 0 ;
  CanTalonSRX *arg1 = (CanTalonSRX *) 0 ;
  int arg2 ;
  CTR_Code result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CanTalonSRX **)&jarg1; 
  arg2 = (int)jarg2; 
  result = (arg1)->SetSelectlFeedbackDevice(arg2);
  *(CTR_Code **)&jresult = new CTR_Code((const CTR_Code &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_wpi_first_wpilibj_hal_CanTalonJNI_CanTalonSRX_1SetRevMotDuringCloseLoopEn(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jlong jresult = 0 ;
  CanTalonSRX *arg1 = (CanTalonSRX *) 0 ;
  int arg2 ;
  CTR_Code result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CanTalonSRX **)&jarg1; 
  arg2 = (int)jarg2; 
  result = (arg1)->SetRevMotDuringCloseLoopEn(arg2);
  *(CTR_Code **)&jresult = new CTR_Code((const CTR_Code &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_wpi_first_wpilibj_hal_CanTalonJNI_CanTalonSRX_1SetBrakeType(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jlong jresult = 0 ;
  CanTalonSRX *arg1 = (CanTalonSRX *) 0 ;
  int arg2 ;
  CTR_Code result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CanTalonSRX **)&jarg1; 
  arg2 = (int)jarg2; 
  result = (arg1)->SetBrakeType(arg2);
  *(CTR_Code **)&jresult = new CTR_Code((const CTR_Code &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_wpi_first_wpilibj_hal_CanTalonJNI_CanTalonSRX_1SetModeSelect(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jlong jresult = 0 ;
  CanTalonSRX *arg1 = (CanTalonSRX *) 0 ;
  int arg2 ;
  CTR_Code result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CanTalonSRX **)&jarg1; 
  arg2 = (int)jarg2; 
  result = (arg1)->SetModeSelect(arg2);
  *(CTR_Code **)&jresult = new CTR_Code((const CTR_Code &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_wpi_first_wpilibj_hal_CanTalonJNI_CanTalonSRX_1SetCloseLoopCellSelect(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jlong jresult = 0 ;
  CanTalonSRX *arg1 = (CanTalonSRX *) 0 ;
  int arg2 ;
  CTR_Code result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CanTalonSRX **)&jarg1; 
  arg2 = (int)jarg2; 
  result = (arg1)->SetCloseLoopCellSelect(arg2);
  *(CTR_Code **)&jresult = new CTR_Code((const CTR_Code &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_wpi_first_wpilibj_hal_CanTalonJNI_CanTalonSRX_1SetRampThrottle(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jlong jresult = 0 ;
  CanTalonSRX *arg1 = (CanTalonSRX *) 0 ;
  int arg2 ;
  CTR_Code result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CanTalonSRX **)&jarg1; 
  arg2 = (int)jarg2; 
  result = (arg1)->SetRampThrottle(arg2);
  *(CTR_Code **)&jresult = new CTR_Code((const CTR_Code &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_wpi_first_wpilibj_hal_CanTalonJNI_CanTalonSRX_1SetRevEncoderPosAndVel(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jlong jresult = 0 ;
  CanTalonSRX *arg1 = (CanTalonSRX *) 0 ;
  int arg2 ;
  CTR_Code result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CanTalonSRX **)&jarg1; 
  arg2 = (int)jarg2; 
  result = (arg1)->SetRevEncoderPosAndVel(arg2);
  *(CTR_Code **)&jresult = new CTR_Code((const CTR_Code &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_wpi_first_wpilibj_hal_CanTalonJNI_CanTalonSRX_1SWIGUpcast(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jlong baseptr = 0;
    (void)jenv;
    (void)jcls;
    *(CtreCanNode **)&baseptr = *(CanTalonSRX **)&jarg1;
    return baseptr;
}

#ifdef __cplusplus
}
#endif

