syntax = "proto3";

package wpi.proto;

option java_package = "org.wpilib.math.controller.proto.detail";

option java_outer_classname = "ProtobufControllerDescriptor";

option java_multiple_files = true;

message ProtobufArmFeedforward {
  double ks = 1;
  double kg = 2;
  double kv = 3;
  double ka = 4;
  double dt = 5;
}

message ProtobufDifferentialDriveFeedforward {
  double kvLinear = 1;
  double kaLinear = 2;
  double kvAngular = 3;
  double kaAngular = 4;
}

message ProtobufElevatorFeedforward {
  double ks = 1;
  double kg = 2;
  double kv = 3;
  double ka = 4;
  double dt = 5;
}

message ProtobufSimpleMotorFeedforward {
  double ks = 1;
  double kv = 2;
  double ka = 3;
  double dt = 4;
}

message ProtobufDifferentialDriveWheelVoltages {
  double left = 1;
  double right = 2;
}
