load("@bazel_skylib//lib:subpackages.bzl", "subpackages")
load("@rules_pkg//:mappings.bzl", "pkg_files", "strip_prefix")
load("//shared:examplecheck.bzl", "examplecheck_test")

_PACKAGE = package_name()

filegroup(
    name = "sources",
    srcs = [pkg + ":sources" for pkg in subpackages.all()],
)

pkg_files(
    name = "examples",
    srcs = [
        "examples.json",
        ":sources",
    ],
    prefix = "examples",
    strip_prefix = strip_prefix.from_root(_PACKAGE),
    visibility = ["//wpilibcExamples:__pkg__"],
)

examplecheck_test(
    name = "examplecheck",
    srcs = [":sources"],
    config = "examples.json",
    env = {
        "EXAMPLECHECK_FOLDER": _PACKAGE,
        "EXAMPLECHECK_KIND": "examples",
    },
    tags = [
        "smoketest",
    ],
)
