plugins {
    id 'java'
    id 'java-library'
    id "org.ysb33r.doxygen" version "2.0.0"
}

evaluationDependsOn(':apriltag')
evaluationDependsOn(':cameraserver')
evaluationDependsOn(':commandsv3')
evaluationDependsOn(':cscore')
evaluationDependsOn(':datalog')
evaluationDependsOn(':epilogue-runtime')
evaluationDependsOn(':fields')
evaluationDependsOn(':hal')
evaluationDependsOn(':ntcore')
evaluationDependsOn(':wpiannotations')
evaluationDependsOn(':commandsv2')
evaluationDependsOn(':telemetry')
evaluationDependsOn(':tunables')
evaluationDependsOn(':wpilibc')
evaluationDependsOn(':wpilibj')
evaluationDependsOn(':wpimath')
evaluationDependsOn(':wpinet')
evaluationDependsOn(':wpiunits')
evaluationDependsOn(':wpiutil')
evaluationDependsOn(':romiVendordep')
evaluationDependsOn(':xrpVendordep')
evaluationDependsOn(':datalog')
evaluationDependsOn(':drivers')

def baseArtifactIdCpp = 'documentation'
def artifactGroupIdCpp = 'org.wpilib.wpilibc'
def zipBaseNameCpp = makeZipBaseName(artifactGroupIdCpp, baseArtifactIdCpp)

def baseArtifactIdJava = 'documentation'
def artifactGroupIdJava = 'org.wpilib.wpilibj'
def zipBaseNameJava = makeZipBaseName(artifactGroupIdJava, baseArtifactIdJava)

def outputsFolder = file("$project.buildDir/outputs")

def cppProjectZips = []
def cppIncludeRoots = []

cppProjectZips.add(project(':apriltag').cppHeadersZip)
cppProjectZips.add(project(':cameraserver').cppHeadersZip)
cppProjectZips.add(project(':cscore').cppHeadersZip)
cppProjectZips.add(project(':datalog').cppHeadersZip)
cppProjectZips.add(project(':drivers').cppHeadersZip)
cppProjectZips.add(project(':fields').cppHeadersZip)
cppProjectZips.add(project(':hal').cppHeadersZip)
cppProjectZips.add(project(':ntcore').cppHeadersZip)
cppProjectZips.add(project(':commandsv2').cppHeadersZip)
cppProjectZips.add(project(':telemetry').cppHeadersZip)
cppProjectZips.add(project(':tunables').cppHeadersZip)
cppProjectZips.add(project(':wpilibc').cppHeadersZip)
cppProjectZips.add(project(':wpimath').cppHeadersZip)
cppProjectZips.add(project(':wpinet').cppHeadersZip)
cppProjectZips.add(project(':wpiutil').cppHeadersZip)
cppProjectZips.add(project(':romiVendordep').cppHeadersZip)
cppProjectZips.add(project(':xrpVendordep').cppHeadersZip)

doxygen {
    // Doxygen binaries are only provided for x86_64 platforms. Other platforms
    // will need to use a local Doxygen install.
    //
    // executeByVersion() fetches Doxygen binaries from
    // https://frcmaven.wpi.edu/ui/native/generic-release-mirror/doxygen/, which
    // is a mirror of binaries from https://doxygen.nl/download.html.
    //
    // To mirror a new Doxygen version, retrigger the GitHub Actions workflow in
    // https://github.com/wpilibsuite/doxygen-mirror with the desired version
    // number as an input.
    //
    // Ensure theme.css (from https://github.com/jothepro/doxygen-awesome-css)
    // is compatible with Doxygen version when updating.
    executables {
        doxygen {
            // Note: has no effect if not on an x86_64 platform - you need to
            // have a global install available on your PATH for the Doxygen
            // plugin to run.
            executableByVersion('1.15.0')

            String arch = System.getProperty("os.arch");
            if (!(arch.equals("x86_64") || arch.equals("amd64"))) {
                // Search for a local Doxygen install
                executableBySearchPath('doxygen')
            }
        }
    }
}

doxygen.sourceSets.main {
    template = 'Doxyfile'

    cppProjectZips.each {
        doxygenDox.dependsOn it
        sources it.source
        it.ext.includeDirs.each {
            cppIncludeRoots.add(it.absolutePath)
        }
    }

    if (project.hasProperty('docWarningsAsErrors')) {
        // LLVM
        exclude 'wpi/util/Compiler.hpp'
        exclude 'wpi/util/ErrorHandling.hpp'
        exclude 'wpi/util/SmallVector.hpp'
        exclude 'wpi/util/StringExtras.hpp'
        exclude 'wpi/util/raw_ostream.hpp'

        // Sleipnir
        exclude 'sleipnir/optimization/solver/interior_point.hpp'
        exclude 'sleipnir/optimization/solver/newton.hpp'
        exclude 'sleipnir/optimization/solver/sqp.hpp'
        exclude 'sleipnir/optimization/solver/util/feasibility_restoration.hpp'

        // apriltag
        exclude 'apriltag_pose.h'

        // htrie
        exclude 'wpi/util/array-hash/**'
        exclude 'wpi/util/htrie_*.hpp'

        // libuv
        exclude 'uv/**'

        // mpack
        exclude 'wpi/util/mpack.h'

        // hat-trie internal helpers
        exclude 'wpi/util/array-hash/**'

        // units
        exclude 'wpi/units/**'
    }

    exclude '*.pb.h'

    // Save space by excluding eigen
    exclude 'Eigen/**'
    exclude 'unsupported/**'

    exclude '**/.clang-tidy'
    exclude '**/.clang-format'

    option 'project_name', 'WPILibC++'
    option 'project_logo', '../wpiutil/src/main/native/resources/wpilib-128.png'
    option 'project_number', wpilibVersioning.version.get()
    option 'strip_from_inc_path', cppIncludeRoots
    option 'strip_from_path', cppIncludeRoots

    if (project.hasProperty('docWarningsAsErrors')) {
        option 'warn_as_error', 'FAIL_ON_WARNINGS_PRINT'
    }
}

tasks.register("zipCppDocs", Zip) {
    archiveBaseName = zipBaseNameCpp
    archiveVersion = ""
    destinationDirectory = outputsFolder
    dependsOn doxygenDox
    from ("$buildDir/docs/doxygen/html")
    into '/'
}

ext {
    useJava = true
    useCpp = false
    skipDev = true
}

// Classpath for everything + OpenCV
apply from: "${rootDir}/shared/opencv.gradle"

def javaDocProjects = [
    project(':allwpilib-java'),
    project(':apriltag'),
    project(':cameraserver'),
    project(':commandsv3'),
    project(':cscore'),
    project(':datalog'),
    project(':drivers'),
    project(':epilogue-runtime'),
    project(':fields'),
    project(':hal'),
    project(':ntcore'),
    project(':telemetry'),
    project(':tunables'),
    project(':wpiannotations'),
    project(':commandsv2'),
    project(':wpilibj'),
    project(':wpimath'),
    project(':wpinet'),
    project(':wpiunits'),
    project(':wpiutil'),
    project(':romiVendordep'),
    project(':xrpVendordep'),
]

// Tracks module-info files to generate per-module javadoc subdirectories.
// This requires all the wpilib subprojects to have a module-info file.
def javaDocModules = javaDocProjects.collectEntries {
    def moduleInfoFile = it.file('src/main/java/module-info.java')
    if (!moduleInfoFile.exists()) {
        throw new GradleException("Missing module-info.java for ${it.path}")
    }

    def javaDocModuleDeclarationPattern = ~/(?m)^\s*(?:open\s+)?module\s+([\w.]+)\s*\{/
    def moduleDeclarationMatcher = moduleInfoFile.getText('UTF-8') =~ javaDocModuleDeclarationPattern
    if (!moduleDeclarationMatcher.find()) {
        throw new GradleException("Could not parse module name from ${moduleInfoFile}")
    }

    [(it): moduleDeclarationMatcher.group(1)]
}
def javaDocModuleSourcePath = layout.buildDirectory.dir('tmp/javadocModuleSources')

def stageJavaDocModules = tasks.register('stageJavaDocModules', Sync) {
    into(javaDocModuleSourcePath)
    includeEmptyDirs = false

    javaDocModules.each { javaDocProject, moduleName ->
        // Ensure any generated source files (eg WPILibVersion.java) are present
        dependsOn(javaDocProject.tasks.named('compileJava'))

        // Copy all source files from the subproject to `docs/build/tmp/javadocModuleSources/${module}/`
        from(javaDocProject.sourceSets.main.allJava) {
            include '**/*.java'
            // Exclude JSON serde files generated by avaje.
            // These files have no javadoc and cause the build to fail when `-PdocWarningsAsErrors` is present,
            // but nobody needs to use the classes directly; the jsonb library uses an SPI to find these classes at
            // runtime, and users interact with the jsonb API, not the SPI.
            exclude '**/*JsonAdapter.java', '**/*JsonComponent.java'
            into moduleName
        }
    }

    doLast {
        javaDocModules.each { _, moduleName ->
            def moduleInfoFile = javaDocModuleSourcePath.get().file("${moduleName}/module-info.java").asFile
            if (!moduleInfoFile.exists()) {
                return
            }

            def moduleInfoText = moduleInfoFile.getText('UTF-8').replaceAll(
                    /(?ms)^\s*provides\s+io\.avaje\.jsonb\.spi\.JsonbExtension\s+with\s+.*?;\s*$/,
                    '')

            if (!(moduleInfoText =~ /(?ms)\/\*\*.*?\*\/\s*(?:open\s+)?module\s+/).find()) {
                moduleInfoText = "/**\n * ${moduleName} module.\n */\n${moduleInfoText}"
            }

            moduleInfoFile.text = moduleInfoText
        }
    }
}

tasks.register('generateJavaDocs', Javadoc) {
    dependsOn stageJavaDocModules
    // Track library dependencies so javadoc can link against them
    def javaDocModulePath = files()

    doFirst {
        def modulePathFiles = javaDocProjects.collectMany {
            it.sourceSets.main.compileClasspath.files
        }
        options.modulePath = modulePathFiles
    }

    classpath = files()
    options.links("https://docs.oracle.com/en/java/javase/25/docs/api/")
    // workaround for opencv site blocking javadoc tool. If the link is changed,
    // docs/opencv/element-list must be redownloaded
    options.linksOffline("https://docs.opencv.org/4.10.0/javadoc/", "opencv")
    options.addStringOption("tag", "pre:a:Pre-Condition")
    options.addBooleanOption("Xdoclint/package:" +
            // TODO: v Document these, then remove them from the list
            "-org.wpilib.hardware.hal," +
            "-org.wpilib.hardware.hal.simulation," +
            // TODO: ^ Document these, then remove them from the list
            "-org.wpilib.hardware.hal.struct," +
            "-org.wpilib.math.struct," +
            "-org.wpilib.math.controller.proto," +
            "-org.wpilib.math.controller.proto.detail," +
            "-org.wpilib.math.controller.struct," +
            "-org.wpilib.math.geometry.proto," +
            "-org.wpilib.math.geometry.proto.detail," +
            "-org.wpilib.math.geometry.struct," +
            "-org.wpilib.math.kinematics.proto," +
            "-org.wpilib.math.kinematics.proto.detail," +
            "-org.wpilib.math.kinematics.struct," +
            "-org.wpilib.math.linalg.proto," +
            "-org.wpilib.math.linalg.proto.detail," +
            "-org.wpilib.math.linalg.struct," +
            "-org.wpilib.math.shape.proto," +
            "-org.wpilib.math.shape.proto.detail," +
            "-org.wpilib.math.shape.struct," +
            "-org.wpilib.math.spline.proto," +
            "-org.wpilib.math.spline.proto.detail," +
            "-org.wpilib.math.spline.struct," +
            "-org.wpilib.math.system.proto," +
            "-org.wpilib.math.system.proto.detail," +
            "-org.wpilib.math.system.struct," +
            "-org.wpilib.math.trajectory.proto," +
            "-org.wpilib.math.trajectory.proto.detail," +
            "-org.wpilib.math.trajectory.struct," +
            "-org.wpilib.command3.proto," +
            // The .measure package contains generated source files for which automatic javadoc
            // generation is very difficult to do meaningfully.
            "-org.wpilib.units.measure", true)
    options.addBooleanOption("Xdoclint:html,missing,reference,syntax", true)
    options.addBooleanOption('html5', true)
    options.linkSource(true)
    options.modulePath = javaDocModulePath.files.toList()
    options.addStringOption('-module-source-path', javaDocModuleSourcePath.get().asFile.absolutePath)
    options.addStringOption('-module', javaDocModules.values().join(','))
    dependsOn project(':wpilibj').generateJavaVersion
    source stageJavaDocModules.map {
        it.outputs.files.asFileTree.matching {
            include '**/*.java'
        }
    }
    failOnError = true
    modularity.inferModulePath = true

    title = "WPILib API ${wpilibVersioning.version.get()}"
    ext.entryPoint = "$destinationDir/index.html"

    if (project.hasProperty('docWarningsAsErrors')) {
        options.addBooleanOption('Werror', true)
    }
}

tasks.register("zipJavaDocs", Zip) {
    archiveBaseName = zipBaseNameJava
    archiveVersion = ""
    destinationDirectory = outputsFolder
    dependsOn generateJavaDocs
    from ("$buildDir/docs/javadoc")
    into '/'
}

tasks.register("zipDocs") {
    dependsOn zipCppDocs
    dependsOn zipJavaDocs
}

apply plugin: 'maven-publish'

publishing {
    publications {
        java(MavenPublication) {
            artifact zipJavaDocs

            artifactId = "${baseArtifactIdJava}"
            groupId = artifactGroupIdJava
            version = wpilibVersioning.version.get()
        }
        cpp(MavenPublication) {
            artifact zipCppDocs

            artifactId = "${baseArtifactIdCpp}"
            groupId = artifactGroupIdCpp
            version = wpilibVersioning.version.get()
        }
    }
}
