load("@rules_cc//cc:cc_binary.bzl", "cc_binary")

filegroup(
    name = "sources",
    srcs = glob([
        "cpp/**/*.cpp",
        "include/**/*.hpp",
    ]),
    visibility = [
        "//wpilibcExamples/src/main/cpp/snippets:__pkg__",
    ],
)

cc_binary(
    name = "SelectCommand",
    srcs = [":sources"],
    includes = ["include"],
    tags = [
        "wpi-example",
    ],
    deps = [
        "//commandsv2",
        "//tunables",
        "//wpilibc",
    ],
)
