ext {
    useJava = true
    useCpp = false
    baseId = 'epilogue-processor'
    groupId = 'org.wpilib.epilogue'

    devMain = ''
}

apply from: "${rootDir}/shared/java/javacommon.gradle"

dependencies {
    implementation(project(':epilogue-runtime'))
    api project(':commandsv2')

    implementation(project(':hal'))
    implementation(project(':ntcore'))
    implementation(project(':tunables'))
    implementation(project(':wpilibj'))
    implementation(project(':wpimath'))

    testImplementation libs.compile.testing
}
