load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_java//java:defs.bzl", "java_binary")

cc_binary(
    name = "multiCameraServer",
    srcs = ["src/main/native/cpp/main.cpp"],
    deps = [
        "//cameraserver",
        "//ntcore",
        "//wpiutil",
    ],
)

java_binary(
    name = "multiCameraServer-java",
    srcs = ["src/main/java/org/wpilib/Main.java"],
    main_class = "org.wpilib.Main",
    deps = [
        "//cameraserver:cameraserver-java",
        "//cscore:cscore-java",
        "//ntcore:ntcore-java",
        "@maven//:com_google_code_gson_gson",
    ],
)
