name: "Pull Request Labeler"
on:
  - pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-slim
    steps:
      - uses: actions/labeler@v5
        with:
          sync-labels: true
